//! Generated vendor-binding source of truth for `agents emit-bindings` and
//! `agents validate-bindings`.
//!
//! [`expected_bindings`] returns the canonical (path, content) pairs that the
//! `emit-bindings` command writes and the `validate-bindings` command verifies.
//! [`binding_dirs_for_catalog`] lists the per-vendor binding directories that
//! the catalog file (`docs/reference/platform-bindings.md`) must enumerate.
//!
//! The core logic of both commands lives here as pure functions that take an
//! explicit `root: &Path`, mirroring how `sync_validator` separates logic from
//! the command wrapper. The `run_*` wrappers in `commands::agents` resolve the
//! git root and delegate here, which keeps the byte-exact output contract
//! unit-testable without a real git checkout.

use std::path::Path;

use anyhow::{Error, anyhow};

/// Canonical `.amazonq/cli-agents/ose-default.json` contents (2-space indent,
/// trailing newline).
const OSE_DEFAULT_JSON: &str = r#"{
  "name": "ose-default",
  "description": "Default agent for this repository. Loads the canonical AGENTS.md instructions and all .amazonq/rules files.",
  "resources": [
    "file://AGENTS.md",
    "file://.amazonq/rules/**/*.md"
  ]
}
"#;

/// Canonical `.amazonq/rules/00-agents-md.md` contents (markdownlint-clean,
/// trailing newline).
const AGENTS_MD_RULE: &str = "# Repository Instructions for Amazon Q

This repository's canonical, vendor-neutral instructions for every contributor
and AI coding agent live in `AGENTS.md` at the repository root. Read it first —
it is the single source of truth.

Amazon Q does not yet read the root `AGENTS.md` natively, so this rules file
bridges the gap. It is generated by `rhino-cli agents emit-bindings`; do not edit
it by hand.
";

/// Returns the expected generated binding files in canonical order: the Amazon
/// Q default agent descriptor first, then the rules file that bridges the root
/// `AGENTS.md`. The path strings are repo-relative and are emitted verbatim.
pub fn expected_bindings() -> Vec<(&'static str, &'static str)> {
    vec![
        (".amazonq/cli-agents/ose-default.json", OSE_DEFAULT_JSON),
        (".amazonq/rules/00-agents-md.md", AGENTS_MD_RULE),
    ]
}

/// Returns the per-vendor binding directories whose presence the catalog file
/// must document, in fixed order.
pub fn binding_dirs_for_catalog() -> Vec<&'static str> {
    vec![".claude", ".opencode", ".codex", ".github", ".amazonq"]
}

/// Outcome of [`emit_bindings`]: the per-file lines plus the trailing summary,
/// already assembled into the byte-exact stdout the command prints.
pub struct EmitResult {
    /// Full stdout text, including the trailing summary line and its newline.
    pub output: String,
    /// Number of binding files emitted.
    pub count: usize,
}

/// Computes (and optionally performs) the `emit-bindings` work rooted at
/// `root`.
///
/// For each expected binding, in order: in `dry_run` mode the file is not
/// touched and a `would write {path}` line is produced; otherwise the parent
/// directories are created, `content` bytes are written to `root/path`, and a
/// `wrote {path}` line is produced. A trailing summary line is appended. The
/// returned [`EmitResult::output`] is the exact stdout to print.
pub fn emit_bindings(root: &Path, dry_run: bool) -> Result<EmitResult, Error> {
    let bindings = expected_bindings();
    let count = bindings.len();
    let mut output = String::new();

    for (path, content) in &bindings {
        if dry_run {
            output.push_str(&format!("would write {path}\n"));
        } else {
            let target = root.join(path);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| anyhow!("failed to create {}: {e}", parent.display()))?;
            }
            std::fs::write(&target, content.as_bytes())
                .map_err(|e| anyhow!("failed to write {}: {e}", target.display()))?;
            output.push_str(&format!("wrote {path}\n"));
        }
    }

    if dry_run {
        output.push_str(&format!(
            "emit-bindings: would write {count} binding file(s) (dry-run)\n"
        ));
    } else {
        output.push_str(&format!("emit-bindings: wrote {count} binding file(s)\n"));
    }

    Ok(EmitResult { output, count })
}

/// Outcome of [`validate_bindings`]: the byte-exact stdout plus the problem
/// count used by the command wrapper to decide the exit code.
pub struct ValidateResult {
    /// Full stdout text: drift lines, missing-catalog lines, two summary lines,
    /// and the verdict line.
    pub output: String,
    /// Total problems found (drift + missing-catalog).
    pub problems: usize,
}

/// Computes the `validate-bindings` report rooted at `root`.
///
/// Two checks are performed:
///
/// 1. **binding-parity** — every expected binding file must exist and its bytes
///    must equal the canonical content. Each mismatch (missing or differing)
///    emits a `DRIFT {path}` line.
/// 2. **catalog-coverage** — every binding directory that exists on disk must be
///    named in the catalog text (`docs/reference/platform-bindings.md`). Each
///    existing dir whose name is absent emits a `MISSING-CATALOG {dir}` line.
///
/// The verdict line is `VALIDATION PASSED` when no problems are found, otherwise
/// `VALIDATION FAILED: {n} problem(s)`. [`ValidateResult::problems`] carries the
/// total so the wrapper can return an error.
pub fn validate_bindings(root: &Path) -> ValidateResult {
    let bindings = expected_bindings();
    let n_files = bindings.len();

    // (A) binding-parity.
    let mut drift: Vec<&'static str> = Vec::new();
    for (path, content) in &bindings {
        let target = root.join(path);
        let matches = match std::fs::read(&target) {
            Ok(bytes) => bytes == content.as_bytes(),
            Err(_) => false,
        };
        if !matches {
            drift.push(path);
        }
    }

    // (B) catalog-coverage.
    let catalog_path = root.join("docs/reference/platform-bindings.md");
    let catalog_text = std::fs::read_to_string(&catalog_path).unwrap_or_default();

    let mut missing: Vec<&'static str> = Vec::new();
    let mut dirs_checked = 0usize;
    for dir in binding_dirs_for_catalog() {
        if root.join(dir).is_dir() {
            dirs_checked += 1;
            if !catalog_text.contains(dir) {
                missing.push(dir);
            }
        }
    }

    let drift_count = drift.len();
    let missing_count = missing.len();
    let problems = drift_count + missing_count;

    let mut output = String::new();
    for path in &drift {
        output.push_str(&format!("DRIFT {path}\n"));
    }
    for dir in &missing {
        output.push_str(&format!("MISSING-CATALOG {dir}\n"));
    }
    output.push_str(&format!(
        "binding-parity: {n_files} file(s) checked, {drift_count} drift\n"
    ));
    output.push_str(&format!(
        "catalog-coverage: {dirs_checked} dir(s) checked, {missing_count} missing\n"
    ));
    if problems == 0 {
        output.push_str("VALIDATION PASSED\n");
    } else {
        output.push_str(&format!("VALIDATION FAILED: {problems} problem(s)\n"));
    }

    ValidateResult { output, problems }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;

    /// Writes every expected binding file to `root` with its canonical content.
    fn write_expected(root: &Path) {
        for (path, content) in expected_bindings() {
            let target = root.join(path);
            std::fs::create_dir_all(target.parent().unwrap()).unwrap();
            std::fs::write(&target, content.as_bytes()).unwrap();
        }
    }

    /// Writes a catalog file at `root` containing every binding dir substring.
    fn write_full_catalog(root: &Path) {
        let dir = root.join("docs/reference");
        std::fs::create_dir_all(&dir).unwrap();
        let mut body = String::new();
        for d in binding_dirs_for_catalog() {
            body.push_str("- `");
            body.push_str(d);
            body.push_str("/` binding\n");
        }
        std::fs::write(dir.join("platform-bindings.md"), body).unwrap();
    }

    #[test]
    fn emit_bindings_dry_run_exact_output() {
        let dir = tempfile::tempdir().unwrap();
        let result = emit_bindings(dir.path(), true).unwrap();
        assert_eq!(
            result.output,
            "would write .amazonq/cli-agents/ose-default.json\n\
             would write .amazonq/rules/00-agents-md.md\n\
             emit-bindings: would write 2 binding file(s) (dry-run)\n"
        );
        assert_eq!(result.count, 2);
        // Dry-run must not touch the filesystem.
        assert!(!dir.path().join(".amazonq").exists());
    }

    #[test]
    fn emit_bindings_writes_exact_output_and_files() {
        let dir = tempfile::tempdir().unwrap();
        let result = emit_bindings(dir.path(), false).unwrap();
        assert_eq!(
            result.output,
            "wrote .amazonq/cli-agents/ose-default.json\n\
             wrote .amazonq/rules/00-agents-md.md\n\
             emit-bindings: wrote 2 binding file(s)\n"
        );
        // Files are written with the canonical bytes.
        for (path, content) in expected_bindings() {
            let written = std::fs::read(dir.path().join(path)).unwrap();
            assert_eq!(written, content.as_bytes(), "content mismatch for {path}");
        }
    }

    #[test]
    fn validate_bindings_clean_passes() {
        let dir = tempfile::tempdir().unwrap();
        write_expected(dir.path());
        // Create every binding dir so catalog-coverage checks all five.
        for d in binding_dirs_for_catalog() {
            std::fs::create_dir_all(dir.path().join(d)).unwrap();
        }
        write_full_catalog(dir.path());

        let result = validate_bindings(dir.path());
        assert_eq!(result.problems, 0, "output: {}", result.output);
        assert_eq!(
            result.output,
            "binding-parity: 2 file(s) checked, 0 drift\n\
             catalog-coverage: 5 dir(s) checked, 0 missing\n\
             VALIDATION PASSED\n"
        );
    }

    #[test]
    fn validate_bindings_reports_drift_when_file_mutated() {
        let dir = tempfile::tempdir().unwrap();
        write_expected(dir.path());
        write_full_catalog(dir.path());
        // Mutate one committed file so its bytes diverge from canonical.
        std::fs::write(
            dir.path().join(".amazonq/rules/00-agents-md.md"),
            "tampered\n",
        )
        .unwrap();

        let result = validate_bindings(dir.path());
        assert!(result.problems >= 1, "expected at least one problem");
        assert!(
            result
                .output
                .contains("DRIFT .amazonq/rules/00-agents-md.md\n"),
            "output: {}",
            result.output
        );
        assert!(
            result
                .output
                .contains("binding-parity: 2 file(s) checked, 1 drift\n")
        );
        assert!(result.output.contains(&format!(
            "VALIDATION FAILED: {} problem(s)\n",
            result.problems
        )));
    }

    #[test]
    fn validate_bindings_reports_drift_when_file_missing() {
        let dir = tempfile::tempdir().unwrap();
        // No expected files written at all → both drift.
        write_full_catalog(dir.path());
        let result = validate_bindings(dir.path());
        assert!(
            result
                .output
                .contains("DRIFT .amazonq/cli-agents/ose-default.json\n")
        );
        assert!(
            result
                .output
                .contains("DRIFT .amazonq/rules/00-agents-md.md\n")
        );
        assert!(
            result
                .output
                .contains("binding-parity: 2 file(s) checked, 2 drift\n")
        );
    }

    #[test]
    fn validate_bindings_reports_missing_catalog() {
        let dir = tempfile::tempdir().unwrap();
        // write_expected creates the .amazonq dir (an existing binding dir) ...
        write_expected(dir.path());
        // ... also create .claude so a second dir is present in the catalog.
        std::fs::create_dir_all(dir.path().join(".claude")).unwrap();
        // Catalog names .claude but omits the .amazonq substring.
        let cat = dir.path().join("docs/reference");
        std::fs::create_dir_all(&cat).unwrap();
        std::fs::write(cat.join("platform-bindings.md"), "- `.claude/` only\n").unwrap();

        let result = validate_bindings(dir.path());
        assert!(
            result.output.contains("MISSING-CATALOG .amazonq\n"),
            "output: {}",
            result.output
        );
        // .claude exists and is present; .amazonq exists and is missing.
        assert!(
            result
                .output
                .contains("catalog-coverage: 2 dir(s) checked, 1 missing\n")
        );
        assert!(result.problems >= 1);
    }

    #[test]
    fn validate_bindings_only_checks_existing_dirs() {
        let dir = tempfile::tempdir().unwrap();
        // Do NOT write the expected files (which would materialize .amazonq).
        write_full_catalog(dir.path());
        // No binding dirs created on disk → zero dirs checked, zero missing.
        let result = validate_bindings(dir.path());
        assert!(
            result
                .output
                .contains("catalog-coverage: 0 dir(s) checked, 0 missing\n"),
            "output: {}",
            result.output
        );
        // Without the expected files this is pure catalog-coverage; the binding
        // files are absent so binding-parity reports 2 drift.
        assert!(
            result
                .output
                .contains("binding-parity: 2 file(s) checked, 2 drift\n")
        );
    }
}
