package agents

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// BindingFile describes a single generated binding file: its repo-relative
// path (always forward-slash, POSIX style) and its exact byte content.
type BindingFile struct {
	Path    string
	Content string
}

// amazonQAgentJSON is the verbatim content of the Amazon Q CLI agent
// definition. It is written as an explicit string literal (NOT marshaled
// via encoding/json) so the output is byte-identical to the Rust twin.
const amazonQAgentJSON = `{
  "name": "ose-default",
  "description": "Default agent for this repository. Loads the canonical AGENTS.md instructions and all .amazonq/rules files.",
  "resources": [
    "file://AGENTS.md",
    "file://.amazonq/rules/**/*.md"
  ]
}
`

// amazonQRulesMD is the verbatim content of the Amazon Q rules bridge file.
const amazonQRulesMD = `# Repository Instructions for Amazon Q

This repository's canonical, vendor-neutral instructions for every contributor
and AI coding agent live in ` + "`AGENTS.md`" + ` at the repository root. Read it first —
it is the single source of truth.

Amazon Q does not yet read the root ` + "`AGENTS.md`" + ` natively, so this rules file
bridges the gap. It is generated by ` + "`rhino-cli agents emit-bindings`" + `; do not edit
it by hand.
`

// ExpectedBindings returns the canonical set of generated binding files in
// a fixed, deterministic order. This is the single source of truth shared
// by both emit-bindings and validate-bindings.
func ExpectedBindings() []BindingFile {
	return []BindingFile{
		{
			Path:    ".amazonq/cli-agents/ose-default.json",
			Content: amazonQAgentJSON,
		},
		{
			Path:    ".amazonq/rules/00-agents-md.md",
			Content: amazonQRulesMD,
		},
	}
}

// BindingDirsForCatalog returns, in fixed order, the per-vendor binding
// directories that the platform-bindings catalog is expected to document.
func BindingDirsForCatalog() []string {
	return []string{".claude", ".opencode", ".codex", ".github", ".amazonq"}
}

// EmitBindings produces the binding files described by ExpectedBindings.
//
// When dryRun is true, no files are written; the function only reports what
// it would do. Otherwise it creates parent directories and writes each file's
// content to root/<Path>. The returned string is the exact stdout text
// (including the trailing summary line); separating output construction from
// the command wiring keeps this testable without a real git root.
func EmitBindings(root string, dryRun bool) (string, error) {
	var b strings.Builder
	bindings := ExpectedBindings()

	for _, bf := range bindings {
		if dryRun {
			fmt.Fprintf(&b, "would write %s\n", bf.Path)
			continue
		}

		target := filepath.Join(root, filepath.FromSlash(bf.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return "", fmt.Errorf("failed to create directory for %s: %w", bf.Path, err)
		}
		if err := os.WriteFile(target, []byte(bf.Content), 0o644); err != nil {
			return "", fmt.Errorf("failed to write %s: %w", bf.Path, err)
		}
		fmt.Fprintf(&b, "wrote %s\n", bf.Path)
	}

	if dryRun {
		fmt.Fprintf(&b, "emit-bindings: would write %d binding file(s) (dry-run)\n", len(bindings))
	} else {
		fmt.Fprintf(&b, "emit-bindings: wrote %d binding file(s)\n", len(bindings))
	}

	return b.String(), nil
}

// ValidateBindings checks binding parity and catalog coverage against the
// tree rooted at root.
//
// Check A (binding-parity): for each ExpectedBindings entry, the file at
// root/<Path> must exist and its bytes must equal the expected content;
// otherwise it is reported as drift.
//
// Check B (catalog-coverage): docs/reference/platform-bindings.md is read
// once. For each BindingDirsForCatalog entry that exists as a directory on
// disk, the catalog text must contain that directory name as a substring;
// otherwise it is reported as missing.
//
// The returned string is the exact stdout text. The returned error is
// non-nil when one or more problems (drift + missing) are found.
func ValidateBindings(root string) (string, error) {
	var b strings.Builder

	// Check A: binding parity.
	bindings := ExpectedBindings()
	var drifts []string
	for _, bf := range bindings {
		target := filepath.Join(root, filepath.FromSlash(bf.Path))
		actual, err := os.ReadFile(target)
		if err != nil || string(actual) != bf.Content {
			drifts = append(drifts, bf.Path)
		}
	}

	// Check B: catalog coverage.
	catalogPath := filepath.Join(root, filepath.FromSlash("docs/reference/platform-bindings.md"))
	catalogBytes, _ := os.ReadFile(catalogPath)
	catalog := string(catalogBytes)

	var missing []string
	dirsChecked := 0
	for _, dir := range BindingDirsForCatalog() {
		info, err := os.Stat(filepath.Join(root, dir))
		if err != nil || !info.IsDir() {
			continue
		}
		dirsChecked++
		if !strings.Contains(catalog, dir) {
			missing = append(missing, dir)
		}
	}

	for _, d := range drifts {
		fmt.Fprintf(&b, "DRIFT %s\n", d)
	}
	for _, m := range missing {
		fmt.Fprintf(&b, "MISSING-CATALOG %s\n", m)
	}

	fmt.Fprintf(&b, "binding-parity: %d file(s) checked, %d drift\n", len(bindings), len(drifts))
	fmt.Fprintf(&b, "catalog-coverage: %d dir(s) checked, %d missing\n", dirsChecked, len(missing))

	problems := len(drifts) + len(missing)
	if problems == 0 {
		fmt.Fprint(&b, "VALIDATION PASSED\n")
		return b.String(), nil
	}

	fmt.Fprintf(&b, "VALIDATION FAILED: %d problem(s)\n", problems)
	return b.String(), fmt.Errorf("binding validation failed: %d problem(s)", problems)
}
