defmodule OpenApiCodegen do
  @moduledoc """
  Generates Elixir struct modules from a bundled OpenAPI YAML spec.

  ## Usage

      OpenApiCodegen.generate(
        "path/to/openapi-bundled.yaml",
        "path/to/output_dir",
        namespace: "MyApp.Schemas"
      )

  This reads the `components.schemas` section of the spec and writes one
  `.ex` file per schema into `output_dir/<namespace_dir>/`.

  ## Generated file format

  Each generated file looks like:

      # DO NOT EDIT — generated by OpenApiCodegen from OpenAPI spec.
      defmodule MyApp.Schemas.User do
        @moduledoc false

        @enforce_keys [:id, :username]
        defstruct [:id, :username, email: nil]

        @type t() :: %__MODULE__{
          id: String.t(),
          username: String.t(),
          email: String.t() | nil
        }
      end
  """

  alias OpenApiCodegen.Generator
  alias OpenApiCodegen.Parser

  @default_namespace "GeneratedSchemas"

  @doc """
  Reads the OpenAPI spec at `spec_path`, generates Elixir struct modules for
  every schema in `components.schemas`, and writes them to `output_dir`.

  ## Options

  - `:namespace` — Elixir module namespace prefix (default: `"GeneratedSchemas"`)

  Returns `{:ok, [file_path]}` with the list of written file paths, or
  `{:error, reason}` if parsing fails.

  ## Examples

      iex> {:ok, paths} = OpenApiCodegen.generate(
      ...>   "test/fixtures/sample.yaml",
      ...>   System.tmp_dir!() <> "/codegen_test"
      ...> )
      iex> length(paths) > 0
      true
  """
  @spec generate(String.t(), String.t(), keyword()) :: {:ok, [String.t()]} | {:error, term()}
  def generate(spec_path, output_dir, opts \\ []) do
    namespace = Keyword.get(opts, :namespace, @default_namespace)

    with {:ok, schemas} <- Parser.parse_file(spec_path) do
      results = Enum.map(schemas, &write_schema(&1, namespace, output_dir))
      collect_results(results)
    end
  end

  defp write_schema(schema, namespace, output_dir) do
    case Generator.write_module(schema, namespace, output_dir) do
      :ok -> {:ok, build_file_path(output_dir, namespace, schema.name)}
      {:error, reason} -> {:error, reason}
    end
  end

  defp collect_results(results) do
    case Enum.filter(results, &match?({:error, _}, &1)) do
      [] ->
        paths = Enum.map(results, fn {:ok, path} -> path end)
        {:ok, paths}

      [{:error, first_reason} | _] ->
        {:error, first_reason}
    end
  end

  # Mirrors the path logic in Generator so callers can predict output locations.
  defp build_file_path(output_dir, namespace, schema_name) do
    namespace_dir = namespace |> Macro.underscore()
    file_name = schema_name |> Macro.underscore() |> then(&"#{&1}.ex")
    Path.join([output_dir, namespace_dir, file_name])
  end
end
