/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthTokensRouteImport } from "./routes/_auth/tokens";
import { Route as AuthProfileRouteImport } from "./routes/_auth/profile";
import { Route as AuthAdminRouteImport } from "./routes/_auth/admin";
import { Route as AuthExpensesIndexRouteImport } from "./routes/_auth/expenses/index";
import { Route as AuthExpensesSummaryRouteImport } from "./routes/_auth/expenses/summary";
import { Route as AuthExpensesIdRouteImport } from "./routes/_auth/expenses/$id";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthTokensRoute = AuthTokensRouteImport.update({
  id: "/tokens",
  path: "/tokens",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthRoute,
} as any);
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthRoute,
} as any);
const AuthExpensesIndexRoute = AuthExpensesIndexRouteImport.update({
  id: "/expenses/",
  path: "/expenses/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthExpensesSummaryRoute = AuthExpensesSummaryRouteImport.update({
  id: "/expenses/summary",
  path: "/expenses/summary",
  getParentRoute: () => AuthRoute,
} as any);
const AuthExpensesIdRoute = AuthExpensesIdRouteImport.update({
  id: "/expenses/$id",
  path: "/expenses/$id",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthAdminRoute;
  "/profile": typeof AuthProfileRoute;
  "/tokens": typeof AuthTokensRoute;
  "/expenses/$id": typeof AuthExpensesIdRoute;
  "/expenses/summary": typeof AuthExpensesSummaryRoute;
  "/expenses/": typeof AuthExpensesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthAdminRoute;
  "/profile": typeof AuthProfileRoute;
  "/tokens": typeof AuthTokensRoute;
  "/expenses/$id": typeof AuthExpensesIdRoute;
  "/expenses/summary": typeof AuthExpensesSummaryRoute;
  "/expenses": typeof AuthExpensesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_auth/admin": typeof AuthAdminRoute;
  "/_auth/profile": typeof AuthProfileRoute;
  "/_auth/tokens": typeof AuthTokensRoute;
  "/_auth/expenses/$id": typeof AuthExpensesIdRoute;
  "/_auth/expenses/summary": typeof AuthExpensesSummaryRoute;
  "/_auth/expenses/": typeof AuthExpensesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/admin"
    | "/profile"
    | "/tokens"
    | "/expenses/$id"
    | "/expenses/summary"
    | "/expenses/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/register"
    | "/admin"
    | "/profile"
    | "/tokens"
    | "/expenses/$id"
    | "/expenses/summary"
    | "/expenses";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/login"
    | "/register"
    | "/_auth/admin"
    | "/_auth/profile"
    | "/_auth/tokens"
    | "/_auth/expenses/$id"
    | "/_auth/expenses/summary"
    | "/_auth/expenses/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/tokens": {
      id: "/_auth/tokens";
      path: "/tokens";
      fullPath: "/tokens";
      preLoaderRoute: typeof AuthTokensRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/profile": {
      id: "/_auth/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthProfileRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/admin": {
      id: "/_auth/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthAdminRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/expenses/": {
      id: "/_auth/expenses/";
      path: "/expenses";
      fullPath: "/expenses/";
      preLoaderRoute: typeof AuthExpensesIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/expenses/summary": {
      id: "/_auth/expenses/summary";
      path: "/expenses/summary";
      fullPath: "/expenses/summary";
      preLoaderRoute: typeof AuthExpensesSummaryRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/expenses/$id": {
      id: "/_auth/expenses/$id";
      path: "/expenses/$id";
      fullPath: "/expenses/$id";
      preLoaderRoute: typeof AuthExpensesIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute;
  AuthProfileRoute: typeof AuthProfileRoute;
  AuthTokensRoute: typeof AuthTokensRoute;
  AuthExpensesIdRoute: typeof AuthExpensesIdRoute;
  AuthExpensesSummaryRoute: typeof AuthExpensesSummaryRoute;
  AuthExpensesIndexRoute: typeof AuthExpensesIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthTokensRoute: AuthTokensRoute,
  AuthExpensesIdRoute: AuthExpensesIdRoute,
  AuthExpensesSummaryRoute: AuthExpensesSummaryRoute,
  AuthExpensesIndexRoute: AuthExpensesIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
