//! Binding generator and all-harness parity guard for rhino-cli.
//
// Covers all 11 supported coding-agent harnesses:
//   Generated tier (byte-parity enforced):
//     - OpenCode (.opencode/agents/ mirrors .claude/agents/)
//     - Amazon Q (.amazonq/rules/ + .amazonq/cli-agents/ — static bridge files)
//
//   Native tier (catalog coverage + no-shadowing rule enforced):
//     - Claude Code (.claude/) — source of truth
//     - Codex (.codex/)
//     - Copilot (.github/)
//     - Cursor (.cursor/)
//     - Windsurf (.windsurf/)
//     - Junie (.junie/)
//     - Antigravity/Gemini (GEMINI.md thin-pointer surface)
//     - Pi — no per-repo artifact; catalog prose only
//     - Aider (CONVENTIONS.md thin-pointer surface)
//
// Also validates the color/tier translation maps from validate-cross-vendor-parity.sh
// (invariants 5a/5b), replacing that shell script.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use super::sync_validator::validate_sync;
use super::types::{ValidationCheck, ValidationResult};

/// Relative path of the Amazon Q rules pointer file (POSIX separators; joined
/// onto the repo root for the host filesystem).
pub const AMAZONQ_RULES_POINTER: &str = ".amazonq/rules/00-agents-md.md";

/// Relative path of the Amazon Q default agent definition.
pub const AMAZONQ_AGENT_DEFINITION: &str = ".amazonq/cli-agents/ose-default.json";

/// Deterministic content of the Amazon Q rules pointer file.
const RULES_POINTER_CONTENT: &str = "# Project Instructions Pointer\n\nThe canonical instructions for this repository live in `AGENTS.md` at the repository root.\nRead and follow `AGENTS.md`. This file exists because Amazon Q Developer does not yet read\n`AGENTS.md` natively; the default agent configuration loads `AGENTS.md` via its `resources`.\n\nDo not edit this file by hand — it is generated by `rhino-cli agents emit-bindings`.\n";

/// Deterministic content of the Amazon Q agent definition (2-space indent,
/// trailing newline) so byte-equality stays stable across emit and validate.
const AGENT_DEFINITION_CONTENT: &str = "{\n  \"name\": \"ose-default\",\n  \"description\": \"Loads the repository's canonical AGENTS.md instructions and project rules.\",\n  \"prompt\": \"Follow the canonical repository instructions in AGENTS.md and the rules in .amazonq/rules/.\",\n  \"resources\": [\n    \"file://AGENTS.md\",\n    \"file://.amazonq/rules/**/*.md\"\n  ],\n  \"tools\": [\n    \"*\"\n  ]\n}\n";

/// Known binding directories / files checked for catalog coverage. If a path
/// in this list exists on disk, the platform-bindings catalog must reference it.
/// Covers all 11 supported harnesses:
///   - Claude Code (.claude) — source of truth
///   - `OpenCode` (.opencode) — generated mirror
///   - Amazon Q (.amazonq) — generated bridge
///   - Codex (.codex) — native reads AGENTS.md directly
///   - Copilot (.github) — native reads AGENTS.md directly
///   - Cursor (.cursor) — native-tier, no-shadowing rule
///   - Windsurf (.windsurf) — native-tier, no-shadowing rule
///   - Junie (.junie) — native-tier, no-shadowing rule
///   - Antigravity / Gemini (GEMINI.md) — native-tier thin-pointer surface
///   - Pi — no per-repo artifact (API-configured); listed in catalog prose only
///   - Aider (CONVENTIONS.md) — native-tier thin-pointer surface
pub const KNOWN_BINDING_DIRS: &[&str] = &[
    ".claude",
    ".opencode",
    ".codex",
    ".github",
    ".amazonq",
    ".cursor",
    ".windsurf",
    ".junie",
    "GEMINI.md",
    "CONVENTIONS.md",
];

/// Relative path (from repo root) of the platform-bindings catalog document.
pub const PLATFORM_BINDINGS_CATALOG: &str = "docs/reference/platform-bindings.md";

/// One canonical (relative path, expected content) pair for a generated file.
#[derive(Debug, Clone)]
pub struct BindingFile {
    /// POSIX-style path relative to the repository root (e.g. `.amazonq/rules/00-agents-md.md`).
    pub rel_path: &'static str,
    /// Exact byte content the file must contain.
    pub content: &'static str,
}

/// Single source of truth for both `emit_bindings` and `validate_bindings`.
/// Returns the canonical relative path and exact byte content of every bridge
/// file. The validator stays in lock-step with the emitter because both read
/// these pairs.
#[must_use]
pub fn expected_bindings() -> Vec<BindingFile> {
    vec![
        BindingFile {
            rel_path: AMAZONQ_RULES_POINTER,
            content: RULES_POINTER_CONTENT,
        },
        BindingFile {
            rel_path: AMAZONQ_AGENT_DEFINITION,
            content: AGENT_DEFINITION_CONTENT,
        },
    ]
}

/// Result of emitting the bridge files.
#[derive(Debug, Clone, Default)]
pub struct EmitResult {
    /// Relative paths of the files that were written.
    pub written: Vec<String>,
    /// Wall time for the emit operation.
    pub duration: std::time::Duration,
}

/// Writes every bridge file under `repo_root` with its deterministic content,
/// creating parent directories as needed. Idempotent: overwrites existing
/// files with the canonical bytes.
///
/// # Errors
///
/// Returns an error string if a directory cannot be created or a file cannot
/// be written.
pub fn emit_bindings(repo_root: &Path) -> Result<EmitResult, String> {
    let start = Instant::now();
    let mut result = EmitResult::default();

    for binding in expected_bindings() {
        let abs = join_rel(repo_root, binding.rel_path);
        if let Some(parent) = abs.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("failed to create directory {}: {e}", parent.display()))?;
        }
        fs::write(&abs, binding.content)
            .map_err(|e| format!("failed to write {}: {e}", abs.display()))?;
        result.written.push(binding.rel_path.to_string());
    }

    result.duration = start.elapsed();
    Ok(result)
}

/// Validates all 11 harnesses:
/// - Amazon Q bridge files: byte-for-byte parity with `expected_bindings()`
/// - `OpenCode` mirror: `.opencode/agents/` mirrors `.claude/agents/` (via `validate_sync`)
/// - Catalog coverage: every present binding dir referenced in the platform-bindings doc
/// - No-Codex-agents-dir: `.codex/agents/` must not exist (Codex reads AGENTS.md natively)
/// - Color/tier translation maps: every `color:` and `model:` value in `.claude/agents/*.md`
///   resolves in the governance docs (ported from `validate-cross-vendor-parity.sh` §5a/5b)
#[must_use]
pub fn validate_bindings(repo_root: &Path) -> ValidationResult {
    let start = Instant::now();
    let mut result = ValidationResult::default();

    // Amazon Q static bridge files (byte-parity)
    for binding in expected_bindings() {
        result.tally(validate_binding_file(repo_root, &binding));
    }

    // OpenCode agent mirror parity (.claude/ ↔ .opencode/)
    let sync_result = validate_sync(repo_root);
    for check in sync_result.checks {
        result.tally(check);
    }

    // Catalog coverage for every present known binding dir / file
    for dir in KNOWN_BINDING_DIRS {
        result.tally(validate_catalog_coverage(repo_root, dir));
    }

    result.tally(validate_no_codex_agents_dir(repo_root));

    // Color/tier translation-map coverage (absorbed from validate-cross-vendor-parity.sh §5a/5b)
    for check in validate_color_tier_maps(repo_root) {
        result.tally(check);
    }

    result.duration = start.elapsed();
    result
}

/// Validates that every `color:` and `model:` value used in `.claude/agents/*.md`
/// resolves in the governance translation-map documents (§5a/5b of the
/// cross-vendor parity invariant).
///
/// Returns an empty vec when the agents directory does not exist (nothing to check).
#[allow(clippy::too_many_lines)]
fn validate_color_tier_maps(repo_root: &Path) -> Vec<ValidationCheck> {
    let agents_dir = repo_root.join(".claude").join("agents");
    if !agents_dir.is_dir() {
        return vec![];
    }

    let color_map_path = repo_root.join("repo-governance/development/agents/ai-agents.md");
    let tier_map_path = repo_root.join("repo-governance/development/agents/model-selection.md");

    let color_map = fs::read_to_string(&color_map_path).unwrap_or_default();
    let tier_map = fs::read_to_string(&tier_map_path).unwrap_or_default();

    let mut checks = Vec::new();
    let mut seen_colors = std::collections::BTreeSet::new();
    let mut seen_tiers = std::collections::BTreeSet::new();

    let Ok(entries) = fs::read_dir(&agents_dir) else {
        return vec![];
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        for line in content.lines() {
            if let Some(color) = line.strip_prefix("color:").map(str::trim)
                && !color.is_empty()
            {
                seen_colors.insert(color.to_string());
            }
            if let Some(model) = line.strip_prefix("model:").map(str::trim)
                && !model.is_empty()
            {
                seen_tiers.insert(model.to_string());
            }
        }
    }

    // §5a: color translation map
    let opencode_direct = [
        "primary",
        "success",
        "warning",
        "secondary",
        "error",
        "info",
        "accent",
        "muted",
    ];
    for color in &seen_colors {
        if opencode_direct.contains(&color.as_str()) {
            checks.push(ValidationCheck::passed(
                format!("Color translation: {color}"),
                format!("'{color}' is a valid OpenCode theme token (no mapping needed)"),
            ));
            continue;
        }
        if color_map.contains(&format!("`{color}`")) {
            checks.push(ValidationCheck::passed(
                format!("Color translation: {color}"),
                format!("'{color}' is mapped in ai-agents.md"),
            ));
        } else {
            checks.push(ValidationCheck::failed(
                format!("Color translation: {color}"),
                "color mapped in repo-governance/development/agents/ai-agents.md",
                format!("'{color}' is NOT in the color translation table"),
                format!(
                    "Add a row for '{color}' in the Platform Binding Color Translation table in ai-agents.md"
                ),
            ));
        }
    }
    if seen_colors.is_empty() {
        checks.push(ValidationCheck::passed(
            "Color translation map",
            "No agent color values to verify (no agents or all use theme tokens)",
        ));
    }

    // §5b: capability-tier map
    for tier in &seen_tiers {
        let needle = format!("`{tier}`");
        if tier_map.contains(&needle) || tier_map.contains(&format!("model: {tier}")) {
            checks.push(ValidationCheck::passed(
                format!("Tier mapping: {tier}"),
                format!("'{tier}' is mapped in model-selection.md"),
            ));
        } else {
            checks.push(ValidationCheck::failed(
                format!("Tier mapping: {tier}"),
                "model value mapped in repo-governance/development/agents/model-selection.md",
                format!("'{tier}' is NOT in the capability-tier map"),
                format!(
                    "Add a row for '{tier}' in the capability-tier table in model-selection.md"
                ),
            ));
        }
    }
    if seen_tiers.is_empty() {
        checks.push(ValidationCheck::passed(
            "Capability-tier map",
            "No agent model values to verify (all agents use planning-grade inherit)",
        ));
    }

    checks
}

/// Check that the committed file at `binding.rel_path` has the exact expected bytes.
fn validate_binding_file(repo_root: &Path, binding: &BindingFile) -> ValidationCheck {
    let check_name = format!("Binding: {}", binding.rel_path);
    let abs = join_rel(repo_root, binding.rel_path);

    match fs::read(&abs) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => ValidationCheck::failed(
            check_name,
            "file present and byte-equal to generated content",
            "file missing",
            format!(
                "{} is missing; run `rhino-cli agents emit-bindings`",
                binding.rel_path
            ),
        ),
        Err(e) => ValidationCheck::failed_msg(
            check_name,
            format!("failed to read {}: {e}", binding.rel_path),
        ),
        Ok(actual) => {
            if actual == binding.content.as_bytes() {
                ValidationCheck::passed(
                    check_name,
                    format!("{} matches generated content", binding.rel_path),
                )
            } else {
                ValidationCheck::failed(
                    check_name,
                    "byte-equal to generated content",
                    "content differs from generated bytes",
                    format!(
                        "{} drifted from canonical content; run `rhino-cli agents emit-bindings`",
                        binding.rel_path
                    ),
                )
            }
        }
    }
}

/// Check that `dir` is referenced in the platform-bindings catalog when it exists on disk.
fn validate_catalog_coverage(repo_root: &Path, dir: &str) -> ValidationCheck {
    let check_name = format!("Catalog Coverage: {dir}");
    let dir_path = repo_root.join(strip_leading_slash(dir));

    if !dir_path.exists() {
        return ValidationCheck::passed(
            check_name,
            format!("{dir} absent on disk; no catalog row required"),
        );
    }

    let catalog_path = join_rel(repo_root, PLATFORM_BINDINGS_CATALOG);
    let catalog = match fs::read_to_string(&catalog_path) {
        Ok(c) => c,
        Err(e) => {
            return ValidationCheck::failed_msg(
                check_name,
                format!("failed to read {PLATFORM_BINDINGS_CATALOG}: {e}"),
            );
        }
    };

    if catalog.contains(dir) {
        ValidationCheck::passed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
        )
    } else {
        ValidationCheck::failed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
            format!("{dir} present on disk but absent from catalog"),
            format!(
                "binding dir {dir} exists but is not referenced in {PLATFORM_BINDINGS_CATALOG}; add a catalog row"
            ),
        )
    }
}

/// Check that the non-standard `.codex/agents/` directory does not exist.
/// Codex CLI configures agents via `agents.<name>` sub-tables in
/// `.codex/config.toml`, not via a directory of agent files.
fn validate_no_codex_agents_dir(repo_root: &Path) -> ValidationCheck {
    let check_name = "No Codex Agents Dir: .codex/agents".to_string();
    let dir_path = join_rel(repo_root, ".codex/agents");

    if dir_path.exists() {
        ValidationCheck::failed(
            check_name,
            ".codex/agents absent",
            ".codex/agents present on disk",
            ".codex/agents/ is not an official Codex CLI convention; define agents as \
             `agents.<name>` sub-tables in .codex/config.toml and delete the directory"
                .to_string(),
        )
    } else {
        ValidationCheck::passed(
            check_name,
            ".codex/agents absent; Codex CLI agents configured via config.toml sub-tables"
                .to_string(),
        )
    }
}

/// Joins a POSIX-style relative path onto the repo root for the host FS.
fn join_rel(repo_root: &Path, rel: &str) -> PathBuf {
    let mut path = repo_root.to_path_buf();
    for segment in rel.split('/') {
        if !segment.is_empty() {
            path.push(segment);
        }
    }
    path
}

/// Strip a leading `/` from `s` if present, to allow safe `Path::join`.
fn strip_leading_slash(s: &str) -> &str {
    s.strip_prefix('/').unwrap_or(s)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn write(path: &Path, content: &str) {
        if let Some(p) = path.parent() {
            std::fs::create_dir_all(p).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    /// A catalog body that references every known binding dir, so coverage
    /// passes for whichever dirs the test materializes.
    fn full_catalog() -> String {
        use std::fmt::Write as _;
        let mut s = String::from("# Platform Bindings\n\n");
        for dir in KNOWN_BINDING_DIRS {
            let _ = writeln!(s, "- `{dir}` row");
        }
        s
    }

    #[test]
    fn emit_writes_both_files_with_exact_bytes() {
        let dir = tempdir().unwrap();
        let root = dir.path();

        let r = emit_bindings(root).unwrap();
        assert_eq!(r.written.len(), 2);

        let pointer = std::fs::read(root.join(".amazonq/rules/00-agents-md.md")).unwrap();
        assert_eq!(pointer, RULES_POINTER_CONTENT.as_bytes());

        let def = std::fs::read(root.join(".amazonq/cli-agents/ose-default.json")).unwrap();
        assert_eq!(def, AGENT_DEFINITION_CONTENT.as_bytes());
    }

    #[test]
    fn emit_agent_definition_is_valid_json() {
        let dir = tempdir().unwrap();
        emit_bindings(dir.path()).unwrap();
        let raw = std::fs::read_to_string(dir.path().join(".amazonq/cli-agents/ose-default.json"))
            .unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(parsed["name"], "ose-default");
        assert_eq!(parsed["resources"][0], "file://AGENTS.md");
        assert_eq!(parsed["tools"][0], "*");
        // Trailing newline is required for byte-stability.
        assert!(raw.ends_with("}\n"));
    }

    #[test]
    fn emit_is_idempotent() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        let first = std::fs::read(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();
        emit_bindings(root).unwrap();
        let second = std::fs::read(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn validate_passes_when_files_match() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Only .amazonq + .claude + .opencode exist on disk; reference them in the catalog.
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_mutated() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // Mutate the pointer file.
        write(
            &root.join(AMAZONQ_RULES_POINTER),
            "# Tampered\n\nsomething else\n",
        );

        let result = validate_bindings(root);
        assert!(result.failed_checks >= 1);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name.contains(AMAZONQ_RULES_POINTER))
        );
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_missing() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        std::fs::remove_file(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.actual == "file missing")
        );
    }

    #[test]
    fn validate_fails_when_present_dir_absent_from_catalog() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Materialize a second known binding dir.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        // Catalog references .amazonq but NOT .github.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row only\n",
        );

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name == "Catalog Coverage: .github"),
            "result: {result:#?}"
        );
    }

    #[test]
    fn validate_passes_when_catalog_references_all_present_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_codex_agents_dir_exists() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs, catalog covers all of them.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // `.codex/agents/` is NOT an official Codex CLI convention (the
        // official mechanism is `agents.<name>` sub-tables in config.toml);
        // its presence must fail validation as a regression guard.
        std::fs::create_dir_all(root.join(".codex/agents")).unwrap();

        let result = validate_bindings(root);
        let failed_codex_agents_check = result.checks.iter().find(|c| {
            c.status == "failed"
                && c.message.contains("config.toml")
                && (c.message.contains("sub-table") || c.message.contains("agents.<name>"))
        });
        assert!(
            failed_codex_agents_check.is_some(),
            "expected a failed check whose advice points to config.toml \
             `agents.<name>` sub-tables when .codex/agents exists; result: {result:#?}"
        );
    }

    #[test]
    fn validate_skips_catalog_check_for_absent_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Catalog references .amazonq + .claude + .opencode (present); others are absent.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row\n- `.claude` row\n- `.opencode` row\n",
        );

        let result = validate_bindings(root);
        // .codex/.github/.cursor/.windsurf/.junie/GEMINI.md/CONVENTIONS.md absent → pass.
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn expected_bindings_is_single_source() {
        let bindings = expected_bindings();
        assert_eq!(bindings.len(), 2);
        assert_eq!(bindings[0].rel_path, AMAZONQ_RULES_POINTER);
        assert_eq!(bindings[1].rel_path, AMAZONQ_AGENT_DEFINITION);
    }

    // ---- P1-1b-RED8 → GREEN8: harness bindings validate covers all 11 harnesses ----

    /// Asserts that all 11 supported harnesses are covered by `harness bindings validate`:
    /// - Native-tier dirs in `KNOWN_BINDING_DIRS` (Cursor, Windsurf, Junie, Antigravity, Aider)
    /// - `OpenCode` parity checks appear in `validate_bindings()` result (via `validate_sync`)
    ///   All 11: Claude Code, `OpenCode`, Amazon Q, Codex, Copilot, Cursor, Windsurf, Junie,
    ///   Antigravity, Pi, Aider.
    #[test]
    fn harness_bindings_validate_covers_all_11_harnesses() {
        // Check 1: native-tier dirs are in KNOWN_BINDING_DIRS
        let native_tier = [
            ".cursor",        // Cursor
            ".windsurf",      // Windsurf
            ".junie",         // JetBrains Junie
            "GEMINI.md",      // Google Antigravity
            "CONVENTIONS.md", // Aider
        ];
        for harness in &native_tier {
            assert!(
                KNOWN_BINDING_DIRS.contains(harness),
                "native-tier harness {harness:?} not in KNOWN_BINDING_DIRS; must cover all 11"
            );
        }

        // Check 2: validate_bindings() produces OpenCode-related checks (via validate_sync)
        let dir = tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row\n",
        );
        let result = validate_bindings(root);
        let has_opencode_check = result.checks.iter().any(|c| {
            c.name.to_lowercase().contains("opencode")
                || c.name.to_lowercase().contains("sync")
                || c.name.to_lowercase().contains("agent")
        });
        assert!(
            has_opencode_check,
            "validate_bindings must produce an OpenCode/sync/agent check for all-11-harness coverage; got checks: {:?}",
            result.checks.iter().map(|c| &c.name).collect::<Vec<_>>()
        );
    }
}
