//! Amazon Q Developer binding bridge generator and parity guard.
//
// Amazon Q Developer does not read the repository's canonical `AGENTS.md`
// natively (unlike Claude Code, OpenCode, or Codex). To keep its instruction
// surface in lock-step with `AGENTS.md` we generate a mechanical "bridge":
//
//   - `.amazonq/rules/00-agents-md.md`     — a pointer to `AGENTS.md`
//   - `.amazonq/cli-agents/ose-default.json` — an Amazon Q agent definition
//     whose `resources` pull in `AGENTS.md` and `.amazonq/rules/`
//
// `emit_bindings` writes those files deterministically (idempotent overwrite);
// `validate_bindings` enforces byte-for-byte parity plus catalog coverage so
// the bridge cannot drift. Both share one source of truth — `expected_bindings`
// returns the canonical (path, content) pairs used by emit and validate alike.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use super::types::{ValidationCheck, ValidationResult};

/// Relative path of the Amazon Q rules pointer file (POSIX separators; joined
/// onto the repo root for the host filesystem).
pub const AMAZONQ_RULES_POINTER: &str = ".amazonq/rules/00-agents-md.md";

/// Relative path of the Amazon Q default agent definition.
pub const AMAZONQ_AGENT_DEFINITION: &str = ".amazonq/cli-agents/ose-default.json";

/// Deterministic content of the Amazon Q rules pointer file.
const RULES_POINTER_CONTENT: &str = "# Project Instructions Pointer\n\nThe canonical instructions for this repository live in `AGENTS.md` at the repository root.\nRead and follow `AGENTS.md`. This file exists because Amazon Q Developer does not yet read\n`AGENTS.md` natively; the default agent configuration loads `AGENTS.md` via its `resources`.\n\nDo not edit this file by hand — it is generated by `rhino-cli agents emit-bindings`.\n";

/// Deterministic content of the Amazon Q agent definition (2-space indent,
/// trailing newline) so byte-equality stays stable across emit and validate.
const AGENT_DEFINITION_CONTENT: &str = "{\n  \"name\": \"ose-default\",\n  \"description\": \"Loads the repository's canonical AGENTS.md instructions and project rules.\",\n  \"prompt\": \"Follow the canonical repository instructions in AGENTS.md and the rules in .amazonq/rules/.\",\n  \"resources\": [\n    \"file://AGENTS.md\",\n    \"file://.amazonq/rules/**/*.md\"\n  ],\n  \"tools\": [\n    \"*\"\n  ]\n}\n";

/// Known binding directories checked for catalog coverage. If a directory in
/// this list exists on disk, the platform-bindings catalog must reference it.
pub const KNOWN_BINDING_DIRS: &[&str] = &[".claude", ".opencode", ".codex", ".github", ".amazonq"];

/// Relative path (from repo root) of the platform-bindings catalog document.
pub const PLATFORM_BINDINGS_CATALOG: &str = "docs/reference/platform-bindings.md";

/// One canonical (relative path, expected content) pair for a generated file.
#[derive(Debug, Clone)]
pub struct BindingFile {
    /// POSIX-style path relative to the repository root (e.g. `.amazonq/rules/00-agents-md.md`).
    pub rel_path: &'static str,
    /// Exact byte content the file must contain.
    pub content: &'static str,
}

/// Single source of truth for both `emit_bindings` and `validate_bindings`.
/// Returns the canonical relative path and exact byte content of every bridge
/// file. The validator stays in lock-step with the emitter because both read
/// these pairs.
#[must_use]
pub fn expected_bindings() -> Vec<BindingFile> {
    vec![
        BindingFile {
            rel_path: AMAZONQ_RULES_POINTER,
            content: RULES_POINTER_CONTENT,
        },
        BindingFile {
            rel_path: AMAZONQ_AGENT_DEFINITION,
            content: AGENT_DEFINITION_CONTENT,
        },
    ]
}

/// Result of emitting the bridge files.
#[derive(Debug, Clone, Default)]
pub struct EmitResult {
    /// Relative paths of the files that were written.
    pub written: Vec<String>,
    /// Wall time for the emit operation.
    pub duration: std::time::Duration,
}

/// Writes every bridge file under `repo_root` with its deterministic content,
/// creating parent directories as needed. Idempotent: overwrites existing
/// files with the canonical bytes.
///
/// # Errors
///
/// Returns an error string if a directory cannot be created or a file cannot
/// be written.
pub fn emit_bindings(repo_root: &Path) -> Result<EmitResult, String> {
    let start = Instant::now();
    let mut result = EmitResult::default();

    for binding in expected_bindings() {
        let abs = join_rel(repo_root, binding.rel_path);
        if let Some(parent) = abs.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("failed to create directory {}: {e}", parent.display()))?;
        }
        fs::write(&abs, binding.content)
            .map_err(|e| format!("failed to write {}: {e}", abs.display()))?;
        result.written.push(binding.rel_path.to_string());
    }

    result.duration = start.elapsed();
    Ok(result)
}

/// Validates the committed bridge files against the canonical content and
/// checks that every present known binding directory is referenced in the
/// platform-bindings catalog. Exits the caller non-zero when any check fails.
#[must_use]
pub fn validate_bindings(repo_root: &Path) -> ValidationResult {
    let start = Instant::now();
    let mut result = ValidationResult::default();

    for binding in expected_bindings() {
        result.tally(validate_binding_file(repo_root, &binding));
    }

    for dir in KNOWN_BINDING_DIRS {
        result.tally(validate_catalog_coverage(repo_root, dir));
    }

    result.tally(validate_no_codex_agents_dir(repo_root));

    result.duration = start.elapsed();
    result
}

/// Check that the committed file at `binding.rel_path` has the exact expected bytes.
fn validate_binding_file(repo_root: &Path, binding: &BindingFile) -> ValidationCheck {
    let check_name = format!("Binding: {}", binding.rel_path);
    let abs = join_rel(repo_root, binding.rel_path);

    match fs::read(&abs) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => ValidationCheck::failed(
            check_name,
            "file present and byte-equal to generated content",
            "file missing",
            format!(
                "{} is missing; run `rhino-cli agents emit-bindings`",
                binding.rel_path
            ),
        ),
        Err(e) => ValidationCheck::failed_msg(
            check_name,
            format!("failed to read {}: {e}", binding.rel_path),
        ),
        Ok(actual) => {
            if actual == binding.content.as_bytes() {
                ValidationCheck::passed(
                    check_name,
                    format!("{} matches generated content", binding.rel_path),
                )
            } else {
                ValidationCheck::failed(
                    check_name,
                    "byte-equal to generated content",
                    "content differs from generated bytes",
                    format!(
                        "{} drifted from canonical content; run `rhino-cli agents emit-bindings`",
                        binding.rel_path
                    ),
                )
            }
        }
    }
}

/// Check that `dir` is referenced in the platform-bindings catalog when it exists on disk.
fn validate_catalog_coverage(repo_root: &Path, dir: &str) -> ValidationCheck {
    let check_name = format!("Catalog Coverage: {dir}");
    let dir_path = repo_root.join(strip_leading_slash(dir));

    if !dir_path.exists() {
        return ValidationCheck::passed(
            check_name,
            format!("{dir} absent on disk; no catalog row required"),
        );
    }

    let catalog_path = join_rel(repo_root, PLATFORM_BINDINGS_CATALOG);
    let catalog = match fs::read_to_string(&catalog_path) {
        Ok(c) => c,
        Err(e) => {
            return ValidationCheck::failed_msg(
                check_name,
                format!("failed to read {PLATFORM_BINDINGS_CATALOG}: {e}"),
            );
        }
    };

    if catalog.contains(dir) {
        ValidationCheck::passed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
        )
    } else {
        ValidationCheck::failed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
            format!("{dir} present on disk but absent from catalog"),
            format!(
                "binding dir {dir} exists but is not referenced in {PLATFORM_BINDINGS_CATALOG}; add a catalog row"
            ),
        )
    }
}

/// Check that the non-standard `.codex/agents/` directory does not exist.
/// Codex CLI configures agents via `agents.<name>` sub-tables in
/// `.codex/config.toml`, not via a directory of agent files.
fn validate_no_codex_agents_dir(repo_root: &Path) -> ValidationCheck {
    let check_name = "No Codex Agents Dir: .codex/agents".to_string();
    let dir_path = join_rel(repo_root, ".codex/agents");

    if dir_path.exists() {
        ValidationCheck::failed(
            check_name,
            ".codex/agents absent",
            ".codex/agents present on disk",
            ".codex/agents/ is not an official Codex CLI convention; define agents as \
             `agents.<name>` sub-tables in .codex/config.toml and delete the directory"
                .to_string(),
        )
    } else {
        ValidationCheck::passed(
            check_name,
            ".codex/agents absent; Codex CLI agents configured via config.toml sub-tables"
                .to_string(),
        )
    }
}

/// Joins a POSIX-style relative path onto the repo root for the host FS.
fn join_rel(repo_root: &Path, rel: &str) -> PathBuf {
    let mut path = repo_root.to_path_buf();
    for segment in rel.split('/') {
        if !segment.is_empty() {
            path.push(segment);
        }
    }
    path
}

/// Strip a leading `/` from `s` if present, to allow safe `Path::join`.
fn strip_leading_slash(s: &str) -> &str {
    s.strip_prefix('/').unwrap_or(s)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn write(path: &Path, content: &str) {
        if let Some(p) = path.parent() {
            std::fs::create_dir_all(p).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    /// A catalog body that references every known binding dir, so coverage
    /// passes for whichever dirs the test materializes.
    fn full_catalog() -> String {
        use std::fmt::Write as _;
        let mut s = String::from("# Platform Bindings\n\n");
        for dir in KNOWN_BINDING_DIRS {
            let _ = writeln!(s, "- `{dir}` row");
        }
        s
    }

    #[test]
    fn emit_writes_both_files_with_exact_bytes() {
        let dir = tempdir().unwrap();
        let root = dir.path();

        let r = emit_bindings(root).unwrap();
        assert_eq!(r.written.len(), 2);

        let pointer = std::fs::read(root.join(".amazonq/rules/00-agents-md.md")).unwrap();
        assert_eq!(pointer, RULES_POINTER_CONTENT.as_bytes());

        let def = std::fs::read(root.join(".amazonq/cli-agents/ose-default.json")).unwrap();
        assert_eq!(def, AGENT_DEFINITION_CONTENT.as_bytes());
    }

    #[test]
    fn emit_agent_definition_is_valid_json() {
        let dir = tempdir().unwrap();
        emit_bindings(dir.path()).unwrap();
        let raw = std::fs::read_to_string(dir.path().join(".amazonq/cli-agents/ose-default.json"))
            .unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(parsed["name"], "ose-default");
        assert_eq!(parsed["resources"][0], "file://AGENTS.md");
        assert_eq!(parsed["tools"][0], "*");
        // Trailing newline is required for byte-stability.
        assert!(raw.ends_with("}\n"));
    }

    #[test]
    fn emit_is_idempotent() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        let first = std::fs::read(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();
        emit_bindings(root).unwrap();
        let second = std::fs::read(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn validate_passes_when_files_match() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Only .amazonq exists on disk; reference it in the catalog.
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_mutated() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // Mutate the pointer file.
        write(
            &root.join(AMAZONQ_RULES_POINTER),
            "# Tampered\n\nsomething else\n",
        );

        let result = validate_bindings(root);
        assert!(result.failed_checks >= 1);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name.contains(AMAZONQ_RULES_POINTER))
        );
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_missing() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        std::fs::remove_file(root.join(AMAZONQ_AGENT_DEFINITION)).unwrap();

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.actual == "file missing")
        );
    }

    #[test]
    fn validate_fails_when_present_dir_absent_from_catalog() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Materialize a second known binding dir.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        // Catalog references .amazonq but NOT .github.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row only\n",
        );

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name == "Catalog Coverage: .github"),
            "result: {result:#?}"
        );
    }

    #[test]
    fn validate_passes_when_catalog_references_all_present_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_codex_agents_dir_exists() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs, catalog covers all of them.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // `.codex/agents/` is NOT an official Codex CLI convention (the
        // official mechanism is `agents.<name>` sub-tables in config.toml);
        // its presence must fail validation as a regression guard.
        std::fs::create_dir_all(root.join(".codex/agents")).unwrap();

        let result = validate_bindings(root);
        let failed_codex_agents_check = result.checks.iter().find(|c| {
            c.status == "failed"
                && c.message.contains("config.toml")
                && (c.message.contains("sub-table") || c.message.contains("agents.<name>"))
        });
        assert!(
            failed_codex_agents_check.is_some(),
            "expected a failed check whose advice points to config.toml \
             `agents.<name>` sub-tables when .codex/agents exists; result: {result:#?}"
        );
    }

    #[test]
    fn validate_skips_catalog_check_for_absent_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        emit_bindings(root).unwrap();
        // Empty catalog; only .amazonq exists, so reference just it.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row\n",
        );

        let result = validate_bindings(root);
        // .claude/.opencode/.codex/.github absent → those coverage checks pass.
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn expected_bindings_is_single_source() {
        let bindings = expected_bindings();
        assert_eq!(bindings.len(), 2);
        assert_eq!(bindings[0].rel_path, AMAZONQ_RULES_POINTER);
        assert_eq!(bindings[1].rel_path, AMAZONQ_AGENT_DEFINITION);
    }
}
