//! Binding generator and all-harness parity guard for rhino-cli.
//
// Covers all 11 supported coding-agent harnesses:
//   Generated tier (byte-parity enforced):
//     - OpenCode (.opencode/agents/ mirrors .claude/agents/)
//     - Cursor (.cursor/agents/ mirrors .claude/agents/)
//     - Amazon Q (.amazonq/rules/ + .amazonq/cli-agents/ — static bridge files)
//
//   Native tier (catalog coverage + no-shadowing rule enforced):
//     - Claude Code (.claude/) — source of truth
//     - Codex (.codex/)
//     - Copilot (.github/)
//     - Windsurf (.windsurf/)
//     - Junie (.junie/)
//     - Antigravity/Gemini (GEMINI.md thin-pointer surface)
//     - Pi — no per-repo artifact; catalog prose only
//     - Aider (CONVENTIONS.md thin-pointer surface)
//
// Also validates the color/tier translation maps from validate-cross-vendor-parity.sh
// (invariants 5a/5b), replacing that shell script.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

#[cfg(unix)]
use std::io::{Read as _, Write as _};
#[cfg(unix)]
use std::os::fd::OwnedFd;

use super::sync_validator::{validate_cursor_sync, validate_sync};
use super::types::{ValidationCheck, ValidationResult};
use crate::application::repo_config;

/// Relative path of the Amazon Q rules pointer file (POSIX separators; joined
/// onto the repo root for the host filesystem).
pub const AMAZONQ_RULES_POINTER: &str = ".amazonq/rules/00-agents-md.md";

/// Relative directory for generated Amazon Q agent definitions.
pub const AMAZONQ_AGENT_DEFINITION_DIR: &str = ".amazonq/cli-agents";

/// Deterministic content of the Amazon Q rules pointer file.
const RULES_POINTER_CONTENT: &str = "# Project Instructions Pointer\n\nThe canonical instructions for this repository live in `AGENTS.md` at the repository root.\nRead and follow `AGENTS.md`. This file exists because Amazon Q Developer does not yet read\n`AGENTS.md` natively; the default agent configuration loads `AGENTS.md` via its `resources`.\n\nDo not edit this file by hand — it is generated by `rhino-cli agents emit-bindings`.\n";

/// Known binding directories / files checked for catalog coverage. If a path
/// in this list exists on disk, the platform-bindings catalog must reference it.
/// Covers all 11 supported harnesses:
///   - Claude Code (.claude) — source of truth
///   - `OpenCode` (.opencode) — generated mirror
///   - Amazon Q (.amazonq) — generated bridge
///   - Codex (.codex) — native reads AGENTS.md directly
///   - Copilot (.github) — native reads AGENTS.md directly
///   - Cursor (.cursor) — generated mirror of `.claude/agents/`
///   - Windsurf (.windsurf) — native-tier, no-shadowing rule
///   - Junie (.junie) — native-tier, no-shadowing rule
///   - Antigravity / Gemini (GEMINI.md) — native-tier thin-pointer surface
///   - Pi — no per-repo artifact (API-configured); listed in catalog prose only
///   - Aider (CONVENTIONS.md) — native-tier thin-pointer surface
pub const KNOWN_BINDING_DIRS: &[&str] = &[
    ".claude",
    ".opencode",
    ".codex",
    ".github",
    ".amazonq",
    ".cursor",
    ".windsurf",
    ".junie",
    "GEMINI.md",
    "CONVENTIONS.md",
];

/// Relative path (from repo root) of the platform-bindings catalog document.
pub const PLATFORM_BINDINGS_CATALOG: &str = "docs/reference/platform-bindings.md";

/// One canonical (relative path, expected content) pair for a generated file.
#[derive(Debug, Clone)]
pub struct BindingFile {
    /// POSIX-style path relative to the repository root (e.g. `.amazonq/rules/00-agents-md.md`).
    pub rel_path: String,
    /// Exact byte content the file must contain.
    pub content: String,
}

/// Single source of truth for both `emit_bindings` and `validate_bindings`.
/// Returns the Amazon Q agent name declared in the repository configuration.
fn amazonq_agent_name(repo_root: &Path) -> Result<String, String> {
    let config = repo_config::load(repo_root)
        .map_err(|error| format!("load repo-config.yml for Amazon Q bindings: {error:#}"))?;
    config
        .harness
        .iter()
        .find(|entry| entry.name == "amazonq")
        .and_then(|entry| entry.agent_name.clone())
        .filter(|name| is_kebab_case_identifier(name))
        .ok_or_else(|| {
            "harness.amazonq.agent-name must be a non-empty lowercase kebab-case identifier"
                .to_string()
        })
}

/// Returns `true` when `value` is safe to embed in the generated agent file
/// name and JSON string without adding repository-specific escaping rules.
fn is_kebab_case_identifier(value: &str) -> bool {
    !value.is_empty()
        && !value.starts_with('-')
        && !value.ends_with('-')
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

/// Builds deterministic Amazon Q definition JSON for `agent_name` (2-space
/// indent and trailing newline) so byte-equality stays stable across emit and
/// validate.
fn agent_definition_content(agent_name: &str) -> String {
    format!(
        "{{\n  \"name\": \"{agent_name}\",\n  \"description\": \"Loads the repository's canonical AGENTS.md instructions and project rules.\",\n  \"prompt\": \"Follow the canonical repository instructions in AGENTS.md and the rules in .amazonq/rules/.\",\n  \"resources\": [\n    \"file://AGENTS.md\",\n    \"file://.amazonq/rules/**/*.md\"\n  ],\n  \"tools\": [\n    \"*\"\n  ]\n}}\n"
    )
}

/// Returns the canonical relative paths and exact byte content of every bridge
/// file. The Amazon Q definition name is repository data read from
/// `harness.amazonq.agent-name`; the validator stays in lock-step with the
/// emitter because both read these pairs.
///
/// # Errors
///
/// Returns an error when the repository configuration cannot supply a valid
/// Amazon Q agent definition name.
pub fn expected_bindings(repo_root: &Path) -> Result<Vec<BindingFile>, String> {
    let agent_name = amazonq_agent_name(repo_root)?;
    let agent_definition_path = format!("{AMAZONQ_AGENT_DEFINITION_DIR}/{agent_name}.json");
    Ok(vec![
        BindingFile {
            rel_path: AMAZONQ_RULES_POINTER.to_string(),
            content: RULES_POINTER_CONTENT.to_string(),
        },
        BindingFile {
            rel_path: agent_definition_path,
            content: agent_definition_content(&agent_name),
        },
    ])
}

/// Result of emitting the bridge files.
#[derive(Debug, Clone, Default)]
pub struct EmitResult {
    /// Relative paths of the files that were written.
    pub written: Vec<String>,
    /// Wall time for the emit operation.
    pub duration: std::time::Duration,
}

/// Writes every bridge file under `repo_root` with its deterministic content,
/// creating parent directories as needed. Idempotent: overwrites existing
/// files with the canonical bytes.
///
/// # Errors
///
/// Returns an error string if a directory cannot be created or a file cannot
/// be written.
pub fn emit_bindings(repo_root: &Path) -> Result<EmitResult, String> {
    #[cfg(unix)]
    {
        emit_bindings_no_follow(repo_root)
    }

    #[cfg(not(unix))]
    {
        emit_bindings_with_metadata_checks(repo_root)
    }
}

/// Emit Amazon Q bindings through directory descriptors, so each path lookup
/// is anchored to the repository and rejects symlinks at the kernel boundary.
/// This prevents an attacker from replacing a checked path with a symlink
/// between inspection and write or stale-definition cleanup.
#[cfg(unix)]
fn emit_bindings_no_follow(repo_root: &Path) -> Result<EmitResult, String> {
    let start = Instant::now();
    let mut result = EmitResult::default();
    let bindings = expected_bindings(repo_root)?;
    let agent_name = amazonq_agent_name(repo_root)?;
    let root = open_repository_directory(repo_root)?;
    let amazonq = open_or_create_directory(&root, ".amazonq")?;
    let rules = open_or_create_directory(&amazonq, "rules")?;
    let definitions = open_or_create_directory(&amazonq, "cli-agents")?;

    let [rules_binding, definition_binding] = bindings.as_slice() else {
        return Err(format!(
            "expected exactly 2 Amazon Q binding files (rules pointer + agent definition), got {}",
            bindings.len()
        ));
    };

    write_no_follow_file(&rules, "00-agents-md.md", &rules_binding.content)?;
    write_no_follow_file(
        &definitions,
        &format!("{agent_name}.json"),
        &definition_binding.content,
    )?;
    result.written = bindings
        .iter()
        .map(|binding| binding.rel_path.clone())
        .collect();

    remove_stale_amazonq_definitions_no_follow(&definitions, &agent_name)?;

    result.duration = start.elapsed();
    Ok(result)
}

/// Open the configured repository root as a directory without following a
/// final symlink. Every subsequent lookup is descriptor-relative.
#[cfg(unix)]
fn open_repository_directory(repo_root: &Path) -> Result<OwnedFd, String> {
    use rustix::fs::{CWD, Mode, OFlags, openat};

    openat(
        CWD,
        repo_root,
        OFlags::RDONLY | OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC,
        Mode::empty(),
    )
    .map_err(|error| {
        format!(
            "failed to open repository root {} with symlink protection: {error}",
            repo_root.display()
        )
    })
}

/// Obtain a child directory from a trusted parent descriptor, creating it if
/// absent. A concurrent symlink replacement is rejected by the final
/// descriptor-relative `openat` with `O_NOFOLLOW`.
#[cfg(unix)]
fn open_or_create_directory(parent: &OwnedFd, name: &str) -> Result<OwnedFd, String> {
    use rustix::fs::{Mode, OFlags, mkdirat, openat};
    use rustix::io::Errno;

    let flags = OFlags::RDONLY | OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC;
    match openat(parent, name, flags, Mode::empty()) {
        Ok(directory) => Ok(directory),
        Err(Errno::NOENT) => {
            if let Err(error) = mkdirat(parent, name, Mode::RWXU)
                && error != Errno::EXIST
            {
                return Err(format!(
                    "failed to create Amazon Q binding directory {name} with symlink protection: {error}"
                ));
            }
            openat(parent, name, flags, Mode::empty()).map_err(|error| {
                format!(
                    "failed to open Amazon Q binding directory {name} with symlink protection: {error}"
                )
            })
        }
        Err(error) => Err(format!(
            "failed to open Amazon Q binding directory {name} with symlink protection: {error}"
        )),
    }
}

/// Write a generated file through its parent directory descriptor without
/// resolving a symlink at the final path component.
#[cfg(unix)]
fn write_no_follow_file(parent: &OwnedFd, name: &str, content: &str) -> Result<(), String> {
    use rustix::fs::{Mode, OFlags, openat};

    let file = openat(
        parent,
        name,
        OFlags::WRONLY | OFlags::CREATE | OFlags::TRUNC | OFlags::NOFOLLOW | OFlags::CLOEXEC,
        Mode::RUSR | Mode::WUSR,
    )
    .map_err(|error| {
        format!("failed to open Amazon Q binding file {name} with symlink protection: {error}")
    })?;
    std::fs::File::from(file)
        .write_all(content.as_bytes())
        .map_err(|error| format!("failed to write Amazon Q binding file {name}: {error}"))
}

/// Remove obsolete generated definitions through the trusted definitions
/// directory descriptor. Both inspection and deletion are descriptor-relative
/// and no-follow, so a concurrent path swap cannot delete outside the repo.
#[cfg(unix)]
fn remove_stale_amazonq_definitions_no_follow(
    definitions_dir: &OwnedFd,
    expected_name: &str,
) -> Result<(), String> {
    use rustix::fs::{AtFlags, Dir, unlinkat};

    let expected_file = format!("{expected_name}.json");
    let entries = Dir::read_from(definitions_dir).map_err(|error| {
        format!("failed to list generated Amazon Q definitions safely: {error}")
    })?;
    for entry in entries {
        let entry = entry.map_err(|error| {
            format!("failed to inspect generated Amazon Q definition safely: {error}")
        })?;
        let Ok(file_name) = entry.file_name().to_str() else {
            continue;
        };
        if file_name == expected_file
            || !is_emitter_managed_definition_at(definitions_dir, file_name)
        {
            continue;
        }
        unlinkat(definitions_dir, file_name, AtFlags::empty()).map_err(|error| {
            format!("failed to remove stale generated Amazon Q definition {file_name}: {error}")
        })?;
    }
    Ok(())
}

/// Return whether a descriptor-relative candidate is a regular file whose
/// bytes exactly match a definition that this emitter could have generated.
#[cfg(unix)]
fn is_emitter_managed_definition_at(definitions_dir: &OwnedFd, file_name: &str) -> bool {
    use rustix::fs::{Mode, OFlags, openat};

    let Some(agent_name) = file_name.strip_suffix(".json") else {
        return false;
    };
    if !is_kebab_case_identifier(agent_name) {
        return false;
    }
    let Ok(file) = openat(
        definitions_dir,
        file_name,
        OFlags::RDONLY | OFlags::NOFOLLOW | OFlags::CLOEXEC,
        Mode::empty(),
    ) else {
        return false;
    };
    let mut content = String::new();
    let mut file = std::fs::File::from(file);
    file.metadata().is_ok_and(|metadata| metadata.is_file())
        && file.read_to_string(&mut content).is_ok()
        && content == agent_definition_content(agent_name)
}

/// Fallback emitter for platforms without POSIX descriptor-relative APIs.
/// Unix targets use [`emit_bindings_no_follow`] instead.
#[cfg(not(unix))]
fn emit_bindings_with_metadata_checks(repo_root: &Path) -> Result<EmitResult, String> {
    let start = Instant::now();
    let mut result = EmitResult::default();

    for binding in expected_bindings(repo_root)? {
        reject_symlinked_binding_path(repo_root, &binding.rel_path)?;
        let abs = join_rel(repo_root, &binding.rel_path);
        if let Some(parent) = abs.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("failed to create directory {}: {e}", parent.display()))?;
        }
        reject_symlinked_binding_path(repo_root, &binding.rel_path)?;
        fs::write(&abs, binding.content)
            .map_err(|e| format!("failed to write {}: {e}", abs.display()))?;
        result.written.push(binding.rel_path);
    }

    remove_stale_amazonq_definitions(repo_root)?;

    result.duration = start.elapsed();
    Ok(result)
}

/// Remove obsolete generated Amazon Q agent definitions after a configured
/// `harness.amazonq.agent-name` rename. The definitions directory can also
/// contain custom Amazon Q agents, so a candidate is removed only when its
/// file name and exact contents prove that a previous emitter run generated it.
#[cfg(not(unix))]
fn remove_stale_amazonq_definitions(repo_root: &Path) -> Result<(), String> {
    let expected_name = amazonq_agent_name(repo_root)?;
    let expected_file = format!("{expected_name}.json");
    reject_symlinked_binding_path(repo_root, AMAZONQ_AGENT_DEFINITION_DIR)?;
    let definitions_dir = repo_root.join(AMAZONQ_AGENT_DEFINITION_DIR);
    let entries = fs::read_dir(&definitions_dir).map_err(|error| {
        format!(
            "failed to list generated Amazon Q definitions at {}: {error}",
            definitions_dir.display()
        )
    })?;
    for entry in entries {
        let entry = entry.map_err(|error| {
            format!(
                "failed to inspect generated Amazon Q definition at {}: {error}",
                definitions_dir.display()
            )
        })?;
        let path = entry.path();
        let is_expected = path.file_name().and_then(|name| name.to_str()) == Some(&expected_file);
        if !is_expected && is_emitter_managed_definition(&entry) {
            fs::remove_file(&path).map_err(|error| {
                format!(
                    "failed to remove stale generated Amazon Q definition {}: {error}",
                    path.display()
                )
            })?;
        }
    }
    Ok(())
}

/// Refuse an Amazon Q binding path when an existing component is a symlink.
///
/// Emission and stale-definition cleanup must never traverse a repository path
/// that has been redirected outside the repository. The binding paths are
/// fixed relative paths, so checking each component protects both directory
/// creation and file writes without accepting user-supplied path traversal.
#[cfg(not(unix))]
fn reject_symlinked_binding_path(repo_root: &Path, rel_path: &str) -> Result<(), String> {
    let mut path = repo_root.to_path_buf();
    for segment in rel_path.split('/') {
        if segment.is_empty() {
            continue;
        }
        path.push(segment);
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "refusing Amazon Q binding path {} because {} is a symlink",
                    rel_path,
                    path.display()
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(format!(
                    "failed to inspect Amazon Q binding path {}: {error}",
                    path.display()
                ));
            }
        }
    }
    Ok(())
}

/// Returns whether `entry` is a regular file whose name and exact bytes match
/// a definition that this emitter could have generated. Failed reads and
/// non-regular entries are deliberately treated as unmanaged: cleanup must
/// preserve anything it cannot positively identify as an emitted definition.
#[cfg(not(unix))]
fn is_emitter_managed_definition(entry: &fs::DirEntry) -> bool {
    let Ok(file_type) = entry.file_type() else {
        return false;
    };
    if !file_type.is_file() {
        return false;
    }

    let Some(file_name) = entry.file_name().to_str().map(str::to_owned) else {
        return false;
    };
    let Some(agent_name) = file_name.strip_suffix(".json") else {
        return false;
    };
    if !is_kebab_case_identifier(agent_name) {
        return false;
    }

    fs::read_to_string(entry.path())
        .is_ok_and(|content| content == agent_definition_content(agent_name))
}

/// Validates all 11 harnesses:
/// - Amazon Q bridge files: byte-for-byte parity with `expected_bindings(repo_root)`
/// - `OpenCode` mirror: `.opencode/agents/` mirrors `.claude/agents/` (via `validate_sync`)
/// - Cursor mirror: `.cursor/agents/` mirrors `.claude/agents/` (via `validate_cursor_sync`)
/// - Catalog coverage: every present binding dir referenced in the platform-bindings doc
/// - No-Codex-agents-dir: `.codex/agents/` must not exist (Codex reads AGENTS.md natively)
/// - Color/tier translation maps: every `color:` and `model:` value in `.claude/agents/*.md`
///   resolves in the governance docs (ported from `validate-cross-vendor-parity.sh` §5a/5b)
#[must_use]
pub fn validate_bindings(repo_root: &Path) -> ValidationResult {
    let start = Instant::now();
    let mut result = ValidationResult::default();

    // Amazon Q bridge files (byte-parity with their configured definition name).
    match expected_bindings(repo_root) {
        Ok(bindings) => {
            for binding in &bindings {
                result.tally(validate_binding_file(repo_root, binding));
            }
        }
        Err(error) => result.tally(ValidationCheck::failed_msg(
            "Amazon Q binding configuration",
            error,
        )),
    }

    // OpenCode agent mirror parity (.claude/ ↔ .opencode/)
    let sync_result = validate_sync(repo_root);
    for check in sync_result.checks {
        result.tally(check);
    }

    // Cursor agent mirror parity (.claude/ ↔ .cursor/agents/)
    let cursor_result = validate_cursor_sync(repo_root);
    for check in cursor_result.checks {
        result.tally(check);
    }

    // Catalog coverage for every present known binding dir / file
    for dir in KNOWN_BINDING_DIRS {
        result.tally(validate_catalog_coverage(repo_root, dir));
    }

    result.tally(validate_no_codex_agents_dir(repo_root));

    // Color/tier translation-map coverage (absorbed from validate-cross-vendor-parity.sh §5a/5b)
    for check in validate_color_tier_maps(repo_root) {
        result.tally(check);
    }

    result.duration = start.elapsed();
    result
}

/// Validates that every `color:` and `model:` value used in `.claude/agents/*.md`
/// resolves in the governance translation-map documents (§5a/5b of the
/// cross-vendor parity invariant).
///
/// Returns an empty vec when the agents directory does not exist (nothing to check).
#[allow(clippy::too_many_lines)]
fn validate_color_tier_maps(repo_root: &Path) -> Vec<ValidationCheck> {
    let agents_dir = repo_root.join(".claude").join("agents");
    if !agents_dir.is_dir() {
        return vec![];
    }

    let color_map_path = repo_root.join("repo-governance/development/agents/ai-agents.md");
    let tier_map_path = repo_root.join("repo-governance/development/agents/model-selection.md");

    let color_map = fs::read_to_string(&color_map_path).unwrap_or_default();
    let tier_map = fs::read_to_string(&tier_map_path).unwrap_or_default();

    let mut checks = Vec::new();
    let mut seen_colors = std::collections::BTreeSet::new();
    let mut seen_tiers = std::collections::BTreeSet::new();

    let Ok(entries) = fs::read_dir(&agents_dir) else {
        return vec![];
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        for line in content.lines() {
            if let Some(color) = line.strip_prefix("color:").map(str::trim)
                && !color.is_empty()
            {
                seen_colors.insert(color.to_string());
            }
            if let Some(model) = line.strip_prefix("model:").map(str::trim)
                && !model.is_empty()
            {
                seen_tiers.insert(model.to_string());
            }
        }
    }

    // §5a: color translation map
    let opencode_direct = [
        "primary",
        "success",
        "warning",
        "secondary",
        "error",
        "info",
        "accent",
        "muted",
    ];
    for color in &seen_colors {
        if opencode_direct.contains(&color.as_str()) {
            checks.push(ValidationCheck::passed(
                format!("Color translation: {color}"),
                format!("'{color}' is a valid OpenCode theme token (no mapping needed)"),
            ));
            continue;
        }
        if color_map.contains(&format!("`{color}`")) {
            checks.push(ValidationCheck::passed(
                format!("Color translation: {color}"),
                format!("'{color}' is mapped in ai-agents.md"),
            ));
        } else {
            checks.push(ValidationCheck::failed(
                format!("Color translation: {color}"),
                "color mapped in repo-governance/development/agents/ai-agents.md",
                format!("'{color}' is NOT in the color translation table"),
                format!(
                    "Add a row for '{color}' in the Platform Binding Color Translation table in ai-agents.md"
                ),
            ));
        }
    }
    if seen_colors.is_empty() {
        checks.push(ValidationCheck::passed(
            "Color translation map",
            "No agent color values to verify (no agents or all use theme tokens)",
        ));
    }

    // §5b: capability-tier map
    for tier in &seen_tiers {
        let needle = format!("`{tier}`");
        if tier_map.contains(&needle) || tier_map.contains(&format!("model: {tier}")) {
            checks.push(ValidationCheck::passed(
                format!("Tier mapping: {tier}"),
                format!("'{tier}' is mapped in model-selection.md"),
            ));
        } else {
            checks.push(ValidationCheck::failed(
                format!("Tier mapping: {tier}"),
                "model value mapped in repo-governance/development/agents/model-selection.md",
                format!("'{tier}' is NOT in the capability-tier map"),
                format!(
                    "Add a row for '{tier}' in the capability-tier table in model-selection.md"
                ),
            ));
        }
    }
    if seen_tiers.is_empty() {
        checks.push(ValidationCheck::passed(
            "Capability-tier map",
            "No agent model values to verify (all agents use planning-grade inherit)",
        ));
    }

    checks
}

/// Check that the committed file at `binding.rel_path` has the exact expected bytes.
fn validate_binding_file(repo_root: &Path, binding: &BindingFile) -> ValidationCheck {
    let check_name = format!("Binding: {}", binding.rel_path);
    let abs = join_rel(repo_root, &binding.rel_path);

    match fs::read(&abs) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => ValidationCheck::failed(
            check_name,
            "file present and byte-equal to generated content",
            "file missing",
            format!(
                "{} is missing; run `rhino-cli agents emit-bindings`",
                binding.rel_path
            ),
        ),
        Err(e) => ValidationCheck::failed_msg(
            check_name,
            format!("failed to read {}: {e}", binding.rel_path),
        ),
        Ok(actual) => {
            if actual == binding.content.as_bytes() {
                ValidationCheck::passed(
                    check_name,
                    format!("{} matches generated content", binding.rel_path),
                )
            } else {
                ValidationCheck::failed(
                    check_name,
                    "byte-equal to generated content",
                    "content differs from generated bytes",
                    format!(
                        "{} drifted from canonical content; run `rhino-cli agents emit-bindings`",
                        binding.rel_path
                    ),
                )
            }
        }
    }
}

/// Check that `dir` is referenced in the platform-bindings catalog when it exists on disk.
fn validate_catalog_coverage(repo_root: &Path, dir: &str) -> ValidationCheck {
    let check_name = format!("Catalog Coverage: {dir}");
    let dir_path = repo_root.join(strip_leading_slash(dir));

    if !dir_path.exists() {
        return ValidationCheck::passed(
            check_name,
            format!("{dir} absent on disk; no catalog row required"),
        );
    }

    let catalog_path = join_rel(repo_root, PLATFORM_BINDINGS_CATALOG);
    let catalog = match fs::read_to_string(&catalog_path) {
        Ok(c) => c,
        Err(e) => {
            return ValidationCheck::failed_msg(
                check_name,
                format!("failed to read {PLATFORM_BINDINGS_CATALOG}: {e}"),
            );
        }
    };

    if catalog.contains(dir) {
        ValidationCheck::passed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
        )
    } else {
        ValidationCheck::failed(
            check_name,
            format!("{dir} referenced in {PLATFORM_BINDINGS_CATALOG}"),
            format!("{dir} present on disk but absent from catalog"),
            format!(
                "binding dir {dir} exists but is not referenced in {PLATFORM_BINDINGS_CATALOG}; add a catalog row"
            ),
        )
    }
}

/// Check that the non-standard `.codex/agents/` directory does not exist.
/// Codex CLI configures agents via `agents.<name>` sub-tables in
/// `.codex/config.toml`, not via a directory of agent files.
fn validate_no_codex_agents_dir(repo_root: &Path) -> ValidationCheck {
    let check_name = "No Codex Agents Dir: .codex/agents".to_string();
    let dir_path = join_rel(repo_root, ".codex/agents");

    if dir_path.exists() {
        ValidationCheck::failed(
            check_name,
            ".codex/agents absent",
            ".codex/agents present on disk",
            ".codex/agents/ is not an official Codex CLI convention; define agents as \
             `agents.<name>` sub-tables in .codex/config.toml and delete the directory"
                .to_string(),
        )
    } else {
        ValidationCheck::passed(
            check_name,
            ".codex/agents absent; Codex CLI agents configured via config.toml sub-tables"
                .to_string(),
        )
    }
}

/// Joins a POSIX-style relative path onto the repo root for the host FS.
fn join_rel(repo_root: &Path, rel: &str) -> PathBuf {
    let mut path = repo_root.to_path_buf();
    for segment in rel.split('/') {
        if !segment.is_empty() {
            path.push(segment);
        }
    }
    path
}

/// Strip a leading `/` from `s` if present, to allow safe `Path::join`.
fn strip_leading_slash(s: &str) -> &str {
    s.strip_prefix('/').unwrap_or(s)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn write(path: &Path, content: &str) {
        if let Some(p) = path.parent() {
            std::fs::create_dir_all(p).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    const TEST_AGENT_NAME: &str = "fixture-agent";

    fn write_amazonq_config(root: &Path) {
        write(
            &root.join("repo-config.yml"),
            concat!(
                "harness:\n",
                "  - name: amazonq\n",
                "    tier: generated\n",
                "    agent-name: fixture-agent\n",
                "coverage:\n  projects: []\n",
            ),
        );
    }

    fn agent_definition_path(root: &Path) -> PathBuf {
        root.join(AMAZONQ_AGENT_DEFINITION_DIR)
            .join(format!("{TEST_AGENT_NAME}.json"))
    }

    /// A catalog body that references every known binding dir, so coverage
    /// passes for whichever dirs the test materializes.
    fn full_catalog() -> String {
        use std::fmt::Write as _;
        let mut s = String::from("# Platform Bindings\n\n");
        for dir in KNOWN_BINDING_DIRS {
            let _ = writeln!(s, "- `{dir}` row");
        }
        s
    }

    #[test]
    fn emit_writes_both_files_with_exact_bytes() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);

        let r = emit_bindings(root).unwrap();
        assert_eq!(r.written.len(), 2);

        let pointer = std::fs::read(root.join(".amazonq/rules/00-agents-md.md")).unwrap();
        assert_eq!(pointer, RULES_POINTER_CONTENT.as_bytes());

        let def = std::fs::read(agent_definition_path(root)).unwrap();
        assert_eq!(def, agent_definition_content(TEST_AGENT_NAME).as_bytes());
    }

    #[test]
    fn emit_agent_definition_is_valid_json() {
        let dir = tempdir().unwrap();
        write_amazonq_config(dir.path());
        emit_bindings(dir.path()).unwrap();
        let raw = std::fs::read_to_string(agent_definition_path(dir.path())).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(parsed["name"], TEST_AGENT_NAME);
        assert_eq!(parsed["resources"][0], "file://AGENTS.md");
        assert_eq!(parsed["tools"][0], "*");
        // Trailing newline is required for byte-stability.
        assert!(raw.ends_with("}\n"));
    }

    #[test]
    fn emit_is_idempotent() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).unwrap();
        let first = std::fs::read(agent_definition_path(root)).unwrap();
        emit_bindings(root).unwrap();
        let second = std::fs::read(agent_definition_path(root)).unwrap();
        assert_eq!(first, second);
    }

    #[cfg(unix)]
    #[test]
    fn emit_refuses_a_symlinked_amazonq_directory_without_writing_outside_repo() {
        use std::os::unix::fs::symlink;

        let dir = tempdir().unwrap();
        let external = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        symlink(external.path(), root.join(".amazonq")).unwrap();

        let error = emit_bindings(root).expect_err("symlinked Amazon Q directory must be rejected");

        assert!(error.contains("symlink"), "unexpected error: {error}");
        assert!(
            !external.path().join("rules/00-agents-md.md").exists(),
            "emission must not write the rules pointer outside the repository"
        );
        assert!(
            !external
                .path()
                .join("cli-agents/fixture-agent.json")
                .exists(),
            "emission must not write the agent definition outside the repository"
        );
    }

    #[cfg(unix)]
    #[test]
    fn emit_refuses_a_symlinked_definitions_directory_without_deleting_outside_repo() {
        use std::os::unix::fs::symlink;

        let dir = tempdir().unwrap();
        let external = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        let external_definitions = external.path().join("cli-agents");
        std::fs::create_dir_all(&external_definitions).unwrap();
        let stale_definition = external_definitions.join("stale-agent.json");
        write(&stale_definition, &agent_definition_content("stale-agent"));
        std::fs::create_dir_all(root.join(".amazonq")).unwrap();
        symlink(
            &external_definitions,
            root.join(AMAZONQ_AGENT_DEFINITION_DIR),
        )
        .unwrap();

        let error = emit_bindings(root)
            .expect_err("symlinked Amazon Q definitions directory must be rejected");

        assert!(error.contains("symlink"), "unexpected error: {error}");
        assert_eq!(
            std::fs::read_to_string(&stale_definition).unwrap(),
            agent_definition_content("stale-agent"),
            "cleanup must not delete a managed-looking definition outside the repository"
        );
        assert!(
            !external_definitions.join("fixture-agent.json").exists(),
            "emission must not create a definition outside the repository"
        );
    }

    #[test]
    fn emit_removes_stale_definition_after_configured_agent_rename() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).expect("emit original definition");
        assert!(agent_definition_path(root).is_file());

        write(
            &root.join("repo-config.yml"),
            concat!(
                "harness:\n",
                "  - name: amazonq\n",
                "    tier: generated\n",
                "    agent-name: renamed-agent\n",
                "coverage:\n  projects: []\n",
            ),
        );
        emit_bindings(root).expect("emit renamed definition");

        assert!(
            !agent_definition_path(root).exists(),
            "the old generated definition must not survive a configured rename"
        );
        assert!(
            root.join(AMAZONQ_AGENT_DEFINITION_DIR)
                .join("renamed-agent.json")
                .is_file(),
            "the configured replacement definition must be emitted"
        );
    }

    #[test]
    fn emit_preserves_custom_definition_after_configured_agent_rename() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).expect("emit original definition");

        let custom_definition = root
            .join(AMAZONQ_AGENT_DEFINITION_DIR)
            .join("custom-agent.json");
        let custom_content =
            "{\n  \"name\": \"custom-agent\",\n  \"prompt\": \"Custom agent\"\n}\n";
        write(&custom_definition, custom_content);

        write(
            &root.join("repo-config.yml"),
            concat!(
                "harness:\n",
                "  - name: amazonq\n",
                "    tier: generated\n",
                "    agent-name: renamed-agent\n",
                "coverage:\n  projects: []\n",
            ),
        );
        emit_bindings(root).expect("emit renamed definition");

        assert_eq!(
            std::fs::read_to_string(&custom_definition).unwrap(),
            custom_content,
            "custom Amazon Q definitions must not be treated as stale emitter output"
        );
        assert!(
            !agent_definition_path(root).exists(),
            "the old generated definition must still be cleaned up"
        );
    }

    #[test]
    fn validate_passes_when_files_match() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Only .amazonq + .claude + .opencode exist on disk; reference them in the catalog.
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_mutated() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // Mutate the pointer file.
        write(
            &root.join(AMAZONQ_RULES_POINTER),
            "# Tampered\n\nsomething else\n",
        );

        let result = validate_bindings(root);
        assert!(result.failed_checks >= 1);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name.contains(AMAZONQ_RULES_POINTER))
        );
    }

    #[test]
    fn validate_fails_when_a_bridge_file_is_missing() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        std::fs::remove_file(agent_definition_path(root)).unwrap();

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.actual == "file missing")
        );
    }

    #[test]
    fn validate_fails_when_present_dir_absent_from_catalog() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).unwrap();
        // Materialize a second known binding dir.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        // Catalog references .amazonq but NOT .github.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row only\n",
        );

        let result = validate_bindings(root);
        assert!(
            result
                .checks
                .iter()
                .any(|c| c.status == "failed" && c.name == "Catalog Coverage: .github"),
            "result: {result:#?}"
        );
    }

    #[test]
    fn validate_passes_when_catalog_references_all_present_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        let result = validate_bindings(root);
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn validate_fails_when_codex_agents_dir_exists() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        emit_bindings(root).unwrap();
        // Materialize several known binding dirs, catalog covers all of them.
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::create_dir_all(root.join(".codex")).unwrap();
        write(&root.join(PLATFORM_BINDINGS_CATALOG), &full_catalog());

        // `.codex/agents/` is NOT an official Codex CLI convention (the
        // official mechanism is `agents.<name>` sub-tables in config.toml);
        // its presence must fail validation as a regression guard.
        std::fs::create_dir_all(root.join(".codex/agents")).unwrap();

        let result = validate_bindings(root);
        let failed_codex_agents_check = result.checks.iter().find(|c| {
            c.status == "failed"
                && c.message.contains("config.toml")
                && (c.message.contains("sub-table") || c.message.contains("agents.<name>"))
        });
        assert!(
            failed_codex_agents_check.is_some(),
            "expected a failed check whose advice points to config.toml \
             `agents.<name>` sub-tables when .codex/agents exists; result: {result:#?}"
        );
    }

    #[test]
    fn validate_skips_catalog_check_for_absent_dirs() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        // Provide empty .claude/agents/ and .opencode/agents/ for OpenCode sync check.
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        // Catalog references .amazonq + .claude + .opencode (present); others are absent.
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row\n- `.claude` row\n- `.opencode` row\n",
        );

        let result = validate_bindings(root);
        // .codex/.github/.cursor/.windsurf/.junie/GEMINI.md/CONVENTIONS.md absent → pass.
        assert_eq!(result.failed_checks, 0, "result: {result:#?}");
    }

    #[test]
    fn expected_bindings_is_single_source() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        let bindings = expected_bindings(root).unwrap();
        assert_eq!(bindings.len(), 2);
        assert_eq!(bindings[0].rel_path, AMAZONQ_RULES_POINTER);
        assert_eq!(
            bindings[1].rel_path,
            format!("{AMAZONQ_AGENT_DEFINITION_DIR}/{TEST_AGENT_NAME}.json")
        );
    }

    #[test]
    fn expected_bindings_rejects_an_unsafe_configured_agent_name() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join("repo-config.yml"),
            concat!(
                "harness:\n",
                "  - name: amazonq\n",
                "    tier: generated\n",
                "    agent-name: ../unsafe\n",
                "coverage:\n  projects: []\n",
            ),
        );

        let error = expected_bindings(root).expect_err("unsafe agent name must be rejected");
        assert!(error.contains("lowercase kebab-case"));
    }

    // ---- P1-1b-RED8 → GREEN8: harness bindings validate covers all 11 harnesses ----

    /// Asserts that all 11 supported harnesses are covered by `harness bindings validate`:
    /// - Native-tier dirs in `KNOWN_BINDING_DIRS` (Cursor, Windsurf, Junie, Antigravity, Aider)
    /// - `OpenCode` parity checks appear in `validate_bindings()` result (via `validate_sync`)
    ///   All 11: Claude Code, `OpenCode`, Amazon Q, Codex, Copilot, Cursor, Windsurf, Junie,
    ///   Antigravity, Pi, Aider.
    #[test]
    fn harness_bindings_validate_covers_all_11_harnesses() {
        // Check 1: native-tier dirs are in KNOWN_BINDING_DIRS
        let native_tier = [
            ".cursor",        // Cursor
            ".windsurf",      // Windsurf
            ".junie",         // JetBrains Junie
            "GEMINI.md",      // Google Antigravity
            "CONVENTIONS.md", // Aider
        ];
        for harness in &native_tier {
            assert!(
                KNOWN_BINDING_DIRS.contains(harness),
                "native-tier harness {harness:?} not in KNOWN_BINDING_DIRS; must cover all 11"
            );
        }

        // Check 2: validate_bindings() produces OpenCode-related checks (via validate_sync)
        let dir = tempdir().unwrap();
        let root = dir.path();
        write_amazonq_config(root);
        std::fs::create_dir_all(root.join(".claude/agents")).unwrap();
        std::fs::create_dir_all(root.join(".opencode/agents")).unwrap();
        emit_bindings(root).unwrap();
        write(
            &root.join(PLATFORM_BINDINGS_CATALOG),
            "# Platform Bindings\n\n- `.amazonq` row\n",
        );
        let result = validate_bindings(root);
        let has_opencode_check = result.checks.iter().any(|c| {
            c.name.to_lowercase().contains("opencode")
                || c.name.to_lowercase().contains("sync")
                || c.name.to_lowercase().contains("agent")
        });
        assert!(
            has_opencode_check,
            "validate_bindings must produce an OpenCode/sync/agent check for all-11-harness coverage; got checks: {:?}",
            result.checks.iter().map(|c| &c.name).collect::<Vec<_>>()
        );
    }
}
