targets:
  $default:
    builders:
      bdd_widget_test|featureBuilder:
        generate_for:
          - test/unit/**
        options:
          features:
            - ../../specs/apps/demo/fe/gherkin
