// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/tokens": {
    params: {};
  };
  "/expenses": {
    params: {};
  };
  "/expenses/new": {
    params: {};
  };
  "/expenses/summary": {
    params: {};
  };
  "/expenses/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/profile" | "/admin" | "/tokens" | "/expenses" | "/expenses/new" | "/expenses/summary" | "/expenses/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/tokens.tsx": {
    id: "routes/tokens";
    page: "/tokens";
  };
  "routes/expenses._index.tsx": {
    id: "routes/expenses._index";
    page: "/expenses";
  };
  "routes/expenses.new.tsx": {
    id: "routes/expenses.new";
    page: "/expenses/new";
  };
  "routes/expenses.summary.tsx": {
    id: "routes/expenses.summary";
    page: "/expenses/summary";
  };
  "routes/expenses.$id.tsx": {
    id: "routes/expenses.$id";
    page: "/expenses/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/tokens": typeof import("./app/routes/tokens.tsx");
  "routes/expenses._index": typeof import("./app/routes/expenses._index.tsx");
  "routes/expenses.new": typeof import("./app/routes/expenses.new.tsx");
  "routes/expenses.summary": typeof import("./app/routes/expenses.summary.tsx");
  "routes/expenses.$id": typeof import("./app/routes/expenses.$id.tsx");
};