defmodule OpenApiCodegen.Generator do
  @moduledoc """
  Generates Elixir struct module source code from parsed OpenAPI schema definitions.

  Produces one `.ex` file per schema. Each file contains a module with:
  - A "DO NOT EDIT" header comment
  - `@moduledoc false`
  - `@enforce_keys` for all required fields
  - `defstruct` listing all fields (required first, then optional)
  - `@type t()` typespec derived from OpenAPI property types
  """

  @type property :: %{name: String.t(), type: String.t(), nullable: boolean()}
  @type schema :: %{name: String.t(), properties: [property()], required: [String.t()]}

  @doc """
  Generates Elixir source code for a single schema.

  Returns the source code as a string. The caller is responsible for writing it
  to disk.

  ## Examples

      iex> schema = %{
      ...>   name: "User",
      ...>   required: ["id", "name"],
      ...>   properties: [
      ...>     %{name: "id", type: "string", nullable: false},
      ...>     %{name: "name", type: "string", nullable: false},
      ...>     %{name: "age", type: "integer", nullable: true}
      ...>   ]
      ...> }
      iex> code = OpenApiCodegen.Generator.generate_module(schema, "MyApp")
      iex> String.contains?(code, "defmodule MyApp.User")
      true
      iex> String.contains?(code, "@enforce_keys [:id, :name]")
      true
      iex> String.contains?(code, "defstruct")
      true
  """
  @spec generate_module(schema(), String.t()) :: String.t()
  def generate_module(%{name: name, properties: properties, required: required}, namespace) do
    module_name = build_module_name(namespace, name)
    enforce_keys = build_enforce_keys(required)
    struct_fields = build_struct_fields(properties, required)
    type_fields = build_type_fields(properties, required)

    """
    # DO NOT EDIT — generated by OpenApiCodegen from OpenAPI spec.
    # Re-run `OpenApiCodegen.generate/2` to refresh.
    #{module_name}
      @moduledoc false

    #{enforce_keys}\
      defstruct #{struct_fields}

      @type t() :: %__MODULE__{
    #{type_fields}\
          }
    end
    """
  end

  @doc """
  Writes a generated module to disk under `output_dir`.

  The output file path is derived from the module namespace and schema name.
  For example, namespace `"MyApp"` with schema `"UserProfile"` writes to
  `output_dir/my_app/user_profile.ex`.

  Returns `:ok` on success or `{:error, reason}` on failure.
  """
  @spec write_module(schema(), String.t(), String.t()) :: :ok | {:error, term()}
  def write_module(schema, namespace, output_dir) do
    source = generate_module(schema, namespace)
    file_path = build_file_path(output_dir, namespace, schema.name)

    dir = Path.dirname(file_path)

    case File.mkdir_p(dir) do
      :ok -> File.write(file_path, source)
      error -> error
    end
  end

  # ---- private helpers ----

  defp build_module_name(namespace, name) do
    "defmodule #{namespace}.#{name} do"
  end

  defp build_enforce_keys([]), do: ""

  defp build_enforce_keys(required) do
    keys = Enum.map_join(required, ", ", &":#{snake_case(&1)}")
    "  @enforce_keys [#{keys}]\n"
  end

  defp build_struct_fields(properties, required) do
    required_set = MapSet.new(required)

    required_fields =
      properties
      |> Enum.filter(&MapSet.member?(required_set, &1.name))
      |> Enum.map(&":#{snake_case(&1.name)}")

    optional_fields =
      properties
      |> Enum.reject(&MapSet.member?(required_set, &1.name))
      |> Enum.map(&"#{snake_case(&1.name)}: nil")

    all_fields = required_fields ++ optional_fields

    case all_fields do
      [] -> "[]"
      fields -> "[#{Enum.join(fields, ", ")}]"
    end
  end

  defp build_type_fields(properties, required) do
    required_set = MapSet.new(required)

    required_part =
      properties
      |> Enum.filter(&MapSet.member?(required_set, &1.name))
      |> Enum.map(fn p -> "        #{snake_case(p.name)}: #{elixir_type(p.type, false)}" end)

    optional_part =
      properties
      |> Enum.reject(&MapSet.member?(required_set, &1.name))
      |> Enum.map(fn p -> "        #{snake_case(p.name)}: #{elixir_type(p.type, true)}" end)

    all_parts = required_part ++ optional_part

    case all_parts do
      [] ->
        ""

      parts ->
        parts
        |> Enum.map_join(",\n", & &1)
        |> then(&(&1 <> "\n"))
    end
  end

  defp elixir_type("string", false), do: "String.t()"
  defp elixir_type("string", true), do: "String.t() | nil"
  defp elixir_type("integer", false), do: "integer()"
  defp elixir_type("integer", true), do: "integer() | nil"
  defp elixir_type("number", false), do: "float()"
  defp elixir_type("number", true), do: "float() | nil"
  defp elixir_type("boolean", false), do: "boolean()"
  defp elixir_type("boolean", true), do: "boolean() | nil"
  defp elixir_type("array", false), do: "list(any())"
  defp elixir_type("array", true), do: "list(any()) | nil"
  defp elixir_type("object", false), do: "map()"
  defp elixir_type("object", true), do: "map() | nil"
  defp elixir_type(_, false), do: "any()"
  defp elixir_type(_, true), do: "any() | nil"

  defp build_file_path(output_dir, namespace, schema_name) do
    namespace_dir = namespace |> Macro.underscore()
    file_name = schema_name |> Macro.underscore() |> then(&"#{&1}.ex")
    Path.join([output_dir, namespace_dir, file_name])
  end

  defp snake_case(name) do
    name
    |> String.replace(~r/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    |> String.replace(~r/([a-z\d])([A-Z])/, "\\1_\\2")
    |> String.downcase()
  end
end
