name: PR - Validate Links

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-docs-links:
    name: Validate markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Run link validation
        run: cargo run --release --quiet --manifest-path apps/rhino-cli-rust/Cargo.toml -- docs validate-links
